// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "black.h"
bool  black_jserialize(const char *file, const black *key){
admJson json;
json.addUint32("startBlack",key->startBlack);
json.addUint32("endBlack",key->endBlack);
return json.dumpToFile(file);
};
bool  black_jdeserialize(const char *file, const ADM_paramList *tmpl,black *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
