int  loadVideo (const char * );
int  clearSegments (void);
int  appendVideo (const char * );
int  addSegment (int ,float , float );
int  setPostProc (int ,int , int );
int  getWidth (void);
int  getHeight (void);
int  getFps1000 (void);
str  getVideoCodec (void);
int  audioReset (void);
int  audioMixer (const char * );
int  clearVideoFilters (void);
int  videoCodec (const char *,couples);
int  audioCodec (const char *,int,couples);
