// Generated by admPyClass.pl do not edit !
//int  jsPrintTiming <int >
tp_obj zzpy_printTiming(TP)
{
int p0=TP_NUM();
int r=jsPrintTiming(p0); 
return tp_number(r);
}
//int  jsDumpSegments <void>
tp_obj zzpy_dumpSegment(TP)
{
int r=jsDumpSegments(); 
return tp_number(r);
}
//int  jsDumpRefVideos <void>
tp_obj zzpy_dumpRefVideo(TP)
{
int r=jsDumpRefVideos(); 
return tp_number(r);
}
static tp_obj myCtorpyEditor(tp_vm *vm)
{
}
tp_obj initClasspyEditor(tp_vm *vm)
{
 tp_obj myClass=tp_class(vm);
 tp_set(vm,myClass,tp_string("__init__"),tp_fnc(vm,myCtorpyEditor));
 tp_set(vm,myClass,tp_string("printTiming"),tp_fnc(vm,zzpy_printTiming));
 tp_set(vm,myClass,tp_string("dumpSegment"),tp_fnc(vm,zzpy_dumpSegment));
 tp_set(vm,myClass,tp_string("dumpRefVideo"),tp_fnc(vm,zzpy_dumpRefVideo));
 return myClass;
}
