// Generated by admPyClass.pl do not edit !
tp_obj zzpy__pyDFToggle_get(tp_vm *vm)
{
  tp_obj self=tp_getraw( vm);
  tinyParams pm(vm);
  ADM_scriptDFToggleHelper *me=(ADM_scriptDFToggleHelper *)pm.asThis(&self,ADM_PYID_DF_TOGGLE);
  char const *key = pm.asString();
  if (!strcmp(key, "value"))
  {
     if(!me) pm.raise("pyDFToggle:No this!");
     return tp_number(me->value());
  }
  return tp_get(vm,self,tp_string(key));
}
tp_obj zzpy__pyDFToggle_set(tp_vm *vm)
{
  tp_obj self=tp_getraw( vm);
  tinyParams pm(vm);
  ADM_scriptDFToggleHelper *me=(ADM_scriptDFToggleHelper *)pm.asThis(&self,ADM_PYID_DF_TOGGLE);
  char const *key = pm.asString();
  if (!strcmp(key, "value"))
  {
     if(!me) pm.raise("pyDFToggle:No this!");
     int val=pm.asInt();
     me->setValue(val);
     return tp_None;
  }
  return tp_None;
}
// Dctor
static void myDtorpyDFToggle(tp_vm *vm,tp_obj self)
{
  ADM_scriptDFToggleHelper *cookie=(ADM_scriptDFToggleHelper *)self.data.val;
  if(cookie) delete cookie;
  self.data.val=NULL;
}
// Ctor (str)
static tp_obj myCtorpyDFToggle(tp_vm *vm)
{
  tp_obj self = tp_getraw(vm);
  tinyParams pm(vm);
  const char *p0= pm.asString();
  ADM_scriptDFToggleHelper *me=new ADM_scriptDFToggleHelper(p0);
  tp_obj cdata = tp_data(vm, ADM_PYID_DF_TOGGLE, me);
  cdata.data.info->xfree = myDtorpyDFToggle;
  tp_set(vm, self, tp_string("cdata"), cdata);
  return tp_None;
}
static tp_obj zzpy__pyDFToggle_help(TP)
 {
};
tp_obj initClasspyDFToggle(tp_vm *vm)
{
  tp_obj myClass=tp_class(vm);
  tp_set(vm,myClass,tp_string("__init__"),tp_fnc(vm,myCtorpyDFToggle));
  tp_set(vm,myClass,tp_string("__set__"),tp_fnc(vm,zzpy__pyDFToggle_set));
  tp_set(vm,myClass,tp_string("__get__"),tp_fnc(vm,zzpy__pyDFToggle_get));
  tp_set(vm,myClass,tp_string("help"),tp_fnc(vm,zzpy__pyDFToggle_help));
  return myClass;
}
