gui=Gui()
red=gui.fileReadSelect("Select a file read")
print(">>>>>>>>>>>>>>>>>>>>>>output"+red+".\n")
red=gui.fileWriteSelect("Select a file write")
print(">>>>>>>>>>>>>>>>>>>>>>output"+red+".\n")
