include(admAsNeeded)
include(admPluginLocation)
MACRO(INIT_VIDEO_FILTER_GTK  lib  _srcsGtk )

  IF(DO_GTK)
    IF(GETTEXT_FOUND)
      ADD_DEFINITIONS("-DHAVE_GETTEXT")
    ENDIF()

    ADD_DEFINITIONS(${GTK_CFLAGS})

    ADM_ADD_SHARED_LIBRARY(${lib} ${ARGN} ${_srcsGtk})
    AS_NEEDED(${lib})
    ADM_TARGET_NO_EXCEPTION(${lib})
    TARGET_LINK_LIBRARIES( ${lib} ADM_UIGtk6 ADM_render6_gtk)
    TARGET_LINK_LIBRARIES(${lib} ${GTK_LDFLAGS} ${GTHREAD_LDFLAGS})
    TARGET_LINK_LIBRARIES(${lib} adm_gettext )

    ADD_TARGET_CFLAGS(${lib} "-DADM_UI_TYPE_BUILD=2")
    INIT_VIDEO_FILTER_INTERNAL(${lib})
    INSTALL_VIDEO_FILTER_INTERNAL(${lib} "gtk")
  ENDIF()
ENDMACRO()
