// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList fdk_encoder_param[]={
 {"bitrate",offsetof(fdk_encoder,bitrate),"uint32_t",ADM_param_uint32_t},
 {"afterburner",offsetof(fdk_encoder,afterburner),"bool",ADM_param_bool},
 {"profile",offsetof(fdk_encoder,profile),"uint32_t",ADM_param_uint32_t},
 {"sbr",offsetof(fdk_encoder,sbr),"bool",ADM_param_bool},
{NULL,0,NULL}
};
