// automatically generated by admSerialization.py do not edit
#ifndef ADM_confChangeFps_CONF_H
#define ADM_confChangeFps_CONF_H
typedef struct {
uint32_t oldMode;
uint32_t oldFpsDen;
uint32_t oldFpsNum;
uint32_t newMode;
uint32_t newFpsDen;
uint32_t newFpsNum;
}confChangeFps;
#endif
