// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList confChangeFps_param[]={
 {"oldMode",offsetof(confChangeFps,oldMode),"uint32_t",ADM_param_uint32_t},
 {"oldFpsDen",offsetof(confChangeFps,oldFpsDen),"uint32_t",ADM_param_uint32_t},
 {"oldFpsNum",offsetof(confChangeFps,oldFpsNum),"uint32_t",ADM_param_uint32_t},
 {"newMode",offsetof(confChangeFps,newMode),"uint32_t",ADM_param_uint32_t},
 {"newFpsDen",offsetof(confChangeFps,newFpsDen),"uint32_t",ADM_param_uint32_t},
 {"newFpsNum",offsetof(confChangeFps,newFpsNum),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
