MACRO(checkQt)
    IF(NOT QT_CHECKED)
        IF(ENABLE_QT6)
            INCLUDE(admCheckQt6)
            checkQt6()
            IF(QT6_FOUND)
                SET(QT_FOUND 1)
            ENDIF()
        ENDIF()
        IF(ENABLE_QT5)
            INCLUDE(admCheckQt5)
            checkQt5()
            IF(QT5_FOUND)
                SET(QT_FOUND 1)
            ENDIF()
        ENDIF()
        IF(ENABLE_QT4)
            INCLUDE(admCheckQt4)
            checkQt4()
            IF(QT4_FOUND)
                SET(QT_FOUND 1)
            ENDIF()
        ENDIF()
        SET(QT_CHECKED 1)
        MESSAGE("")
    ENDIF()
    include(admQtMacro)
ENDMACRO()
