// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList lame_encoder_param[]={
 {"bitrate",offsetof(lame_encoder,bitrate),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
