// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList quadTrans_param[]={
 {"dx1",offsetof(quadTrans,dx1),"float",ADM_param_float},
 {"dy1",offsetof(quadTrans,dy1),"float",ADM_param_float},
 {"dx2",offsetof(quadTrans,dx2),"float",ADM_param_float},
 {"dy2",offsetof(quadTrans,dy2),"float",ADM_param_float},
 {"dx3",offsetof(quadTrans,dx3),"float",ADM_param_float},
 {"dy3",offsetof(quadTrans,dy3),"float",ADM_param_float},
 {"dx4",offsetof(quadTrans,dx4),"float",ADM_param_float},
 {"dy4",offsetof(quadTrans,dy4),"float",ADM_param_float},
 {"zoom",offsetof(quadTrans,zoom),"float",ADM_param_float},
 {"algo",offsetof(quadTrans,algo),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
