// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
float dx1;
float dy1;
float dx2;
float dy2;
float dx3;
float dy3;
float dx4;
float dy4;
float zoom;
uint32_t algo;
}quadTrans;
