// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "artCartoon.h"
bool  artCartoon_jserialize(const char *file, const artCartoon *key){
admJson json;
json.addFloat("threshold",key->threshold);
json.addUint32("scatter",key->scatter);
json.addUint32("color",key->color);
return json.dumpToFile(file);
};
bool  artCartoon_jdeserialize(const char *file, const ADM_paramList *tmpl,artCartoon *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
