// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList artCartoon_param[]={
 {"threshold",offsetof(artCartoon,threshold),"float",ADM_param_float},
 {"scatter",offsetof(artCartoon,scatter),"uint32_t",ADM_param_uint32_t},
 {"color",offsetof(artCartoon,color),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
