// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList lav_param[]={
 {"deintType",offsetof(lav,deintType),"uint32_t",ADM_param_uint32_t},
 {"autoLevel",offsetof(lav,autoLevel),"bool",ADM_param_bool},
{NULL,0,NULL}
};
