// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "flip.h"
bool  flip_jserialize(const char *file, const flip *key){
admJson json;
json.addUint32("flipdir",key->flipdir);
return json.dumpToFile(file);
};
bool  flip_jdeserialize(const char *file, const ADM_paramList *tmpl,flip *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
