// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList shaderLoaderConf_param[]={
 {"shaderFile",offsetof(shaderLoaderConf,shaderFile),"char *",ADM_param_string},
{NULL,0,NULL}
};
