// automatically generated by admSerialization.py do not edit
#ifndef ADM_artVignette_CONF_H
#define ADM_artVignette_CONF_H
typedef struct {
float aspect;
float center;
float soft;
}artVignette;
#endif
