// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList artVignette_param[]={
 {"aspect",offsetof(artVignette,aspect),"float",ADM_param_float},
 {"center",offsetof(artVignette,center),"float",ADM_param_float},
 {"soft",offsetof(artVignette,soft),"float",ADM_param_float},
{NULL,0,NULL}
};
