// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "fieldsAlign.h"
bool  fieldsAlign_jserialize(const char *file, const fieldsAlign *key){
admJson json;
json.addBool("swapFields",key->swapFields);
json.addInt32("topAdjH",key->topAdjH);
json.addInt32("topAdjV",key->topAdjV);
json.addInt32("botAdjH",key->botAdjH);
json.addInt32("botAdjV",key->botAdjV);
return json.dumpToFile(file);
};
bool  fieldsAlign_jdeserialize(const char *file, const ADM_paramList *tmpl,fieldsAlign *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
