// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
bool swapFields;
int32_t topAdjH;
int32_t topAdjV;
int32_t botAdjH;
int32_t botAdjV;
}fieldsAlign;
