// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList fieldsAlign_param[]={
 {"swapFields",offsetof(fieldsAlign,swapFields),"bool",ADM_param_bool},
 {"topAdjH",offsetof(fieldsAlign,topAdjH),"int32_t",ADM_param_int32_t},
 {"topAdjV",offsetof(fieldsAlign,topAdjV),"int32_t",ADM_param_int32_t},
 {"botAdjH",offsetof(fieldsAlign,botAdjH),"int32_t",ADM_param_int32_t},
 {"botAdjV",offsetof(fieldsAlign,botAdjV),"int32_t",ADM_param_int32_t},
{NULL,0,NULL}
};
