// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList delogoHQ_param[]={
 {"maskfile",offsetof(delogoHQ,maskfile),"std::string",ADM_param_stdstring},
 {"blur",offsetof(delogoHQ,blur),"uint32_t",ADM_param_uint32_t},
 {"gradient",offsetof(delogoHQ,gradient),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
