// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList artDynThreshold_param[]={
 {"levels",offsetof(artDynThreshold,levels),"uint32_t",ADM_param_uint32_t},
 {"offset",offsetof(artDynThreshold,offset),"float",ADM_param_float},
{NULL,0,NULL}
};
