// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "aiEnhance.h"
bool  aiEnhance_jserialize(const char *file, const aiEnhance *key){
admJson json;
json.addUint32("algo",key->algo);
return json.dumpToFile(file);
};
bool  aiEnhance_jdeserialize(const char *file, const ADM_paramList *tmpl,aiEnhance *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
