// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
COMPRES_PARAMS ratectl;
uint32_t nbThreads;
uint32_t speed;
uint32_t deadline;
bool fullrange;
}vp9_encoder;
