// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
uint32_t nbThreads;
uint32_t speed;
uint32_t deadline;
uint32_t qMin;
uint32_t qMax;
bool fullrange;
}vp9_encoder;
