// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
float loLuma;
float mdLuma;
float hiLuma;
float loAngle;
float mdAngle;
float hiAngle;
float loShift;
float mdShift;
float hiShift;
float loSaturation;
float mdSaturation;
float hiSaturation;
}colorBalance;
