// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "colorBalance.h"
bool  colorBalance_jserialize(const char *file, const colorBalance *key){
admJson json;
json.addFloat("loLuma",key->loLuma);
json.addFloat("mdLuma",key->mdLuma);
json.addFloat("hiLuma",key->hiLuma);
json.addFloat("loAngle",key->loAngle);
json.addFloat("mdAngle",key->mdAngle);
json.addFloat("hiAngle",key->hiAngle);
json.addFloat("loShift",key->loShift);
json.addFloat("mdShift",key->mdShift);
json.addFloat("hiShift",key->hiShift);
json.addFloat("loSaturation",key->loSaturation);
json.addFloat("mdSaturation",key->mdSaturation);
json.addFloat("hiSaturation",key->hiSaturation);
return json.dumpToFile(file);
};
bool  colorBalance_jdeserialize(const char *file, const ADM_paramList *tmpl,colorBalance *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
