// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList waveletDenoise_param[]={
 {"threshold",offsetof(waveletDenoise,threshold),"float",ADM_param_float},
 {"softness",offsetof(waveletDenoise,softness),"float",ADM_param_float},
 {"highq",offsetof(waveletDenoise,highq),"bool",ADM_param_bool},
 {"chroma",offsetof(waveletDenoise,chroma),"bool",ADM_param_bool},
{NULL,0,NULL}
};
