// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
uint32_t muxerType;
bool faststart;
bool forceAspectRatio;
uint32_t aspectRatio;
uint32_t rotation;
}mp4_muxer;
