// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
uint32_t muxerType;
uint32_t optimize;
bool forceAspectRatio;
uint32_t aspectRatio;
uint32_t displayWidth;
uint32_t rotation;
uint32_t clockfreq;
}mp4_muxer;
