// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList mp4_muxer_param[]={
 {"muxerType",offsetof(mp4_muxer,muxerType),"uint32_t",ADM_param_uint32_t},
 {"optimize",offsetof(mp4_muxer,optimize),"uint32_t",ADM_param_uint32_t},
 {"forceAspectRatio",offsetof(mp4_muxer,forceAspectRatio),"bool",ADM_param_bool},
 {"aspectRatio",offsetof(mp4_muxer,aspectRatio),"uint32_t",ADM_param_uint32_t},
 {"displayWidth",offsetof(mp4_muxer,displayWidth),"uint32_t",ADM_param_uint32_t},
 {"rotation",offsetof(mp4_muxer,rotation),"uint32_t",ADM_param_uint32_t},
 {"clockfreq",offsetof(mp4_muxer,clockfreq),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
