// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList blackenBorder_param[]={
 {"left",offsetof(blackenBorder,left),"uint32_t",ADM_param_uint32_t},
 {"right",offsetof(blackenBorder,right),"uint32_t",ADM_param_uint32_t},
 {"top",offsetof(blackenBorder,top),"uint32_t",ADM_param_uint32_t},
 {"bottom",offsetof(blackenBorder,bottom),"uint32_t",ADM_param_uint32_t},
 {"rubber_is_hidden",offsetof(blackenBorder,rubber_is_hidden),"bool",ADM_param_bool},
{NULL,0,NULL}
};
