// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
uint32_t startTime;
uint32_t endTime;
bool enableBlend;
bool enableSat;
bool enableBlur;
bool enableRot;
bool enableZoom;
bool enableVignette;
uint32_t rgbColorBlend;
uint32_t rgbColorVignette;
float peakBlend;
float peakSat;
float peakBlur;
float peakRot;
float peakZoom;
float peakVignette;
uint32_t transientBlend;
uint32_t transientSat;
uint32_t transientBlur;
uint32_t transientRot;
uint32_t transientZoom;
uint32_t transientVignette;
float transientDurationBlend;
float transientDurationSat;
float transientDurationBlur;
float transientDurationRot;
float transientDurationZoom;
float transientDurationVignette;
}fadeThrough;
