// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "artPixelize.h"
bool  artPixelize_jserialize(const char *file, const artPixelize *key){
admJson json;
json.addUint32("pw",key->pw);
json.addUint32("ph",key->ph);
return json.dumpToFile(file);
};
bool  artPixelize_jdeserialize(const char *file, const ADM_paramList *tmpl,artPixelize *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
