// automatically generated by admSerialization.py do not edit
#ifndef ADM_aften_encoder_CONF_H
#define ADM_aften_encoder_CONF_H
typedef struct {
uint32_t bitrate;
uint32_t mode;
}aften_encoder;
#endif
