// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList aften_encoder_param[]={
 {"bitrate",offsetof(aften_encoder,bitrate),"uint32_t",ADM_param_uint32_t},
 {"mode",offsetof(aften_encoder,mode),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
