// Automatically generated, do not edit!
const ADM_paramList FFcodecContext_param[]={
 {"version",offsetof( FFcodecContext,version),"uint32_t",ADM_param_uint32_t},
 {"MultiThreaded",offsetof( FFcodecContext,MultiThreaded),"uint32_t",ADM_param_uint32_t},
 {"me_method",offsetof( FFcodecContext,me_method),"uint32_t",ADM_param_uint32_t},
 {"_GMC",offsetof( FFcodecContext,_GMC),"uint32_t",ADM_param_uint32_t},
 {"_4MV",offsetof( FFcodecContext,_4MV),"uint32_t",ADM_param_uint32_t},
 {"_QPEL",offsetof( FFcodecContext,_QPEL),"uint32_t",ADM_param_uint32_t},
 {"_TRELLIS_QUANT",offsetof( FFcodecContext,_TRELLIS_QUANT),"uint32_t",ADM_param_uint32_t},
 {"qmin",offsetof( FFcodecContext,qmin),"uint32_t",ADM_param_uint32_t},
 {"qmax",offsetof( FFcodecContext,qmax),"uint32_t",ADM_param_uint32_t},
 {"max_qdiff",offsetof( FFcodecContext,max_qdiff),"uint32_t",ADM_param_uint32_t},
 {"max_b_frames",offsetof( FFcodecContext,max_b_frames),"uint32_t",ADM_param_uint32_t},
 {"mpeg_quant",offsetof( FFcodecContext,mpeg_quant),"uint32_t",ADM_param_uint32_t},
 {"is_luma_elim_threshold",offsetof( FFcodecContext,is_luma_elim_threshold),"uint32_t",ADM_param_uint32_t},
 {"luma_elim_threshold",offsetof( FFcodecContext,luma_elim_threshold),"uint32_t",ADM_param_uint32_t},
 {"is_chroma_elim_threshold",offsetof( FFcodecContext,is_chroma_elim_threshold),"uint32_t",ADM_param_uint32_t},
 {"chroma_elim_threshold",offsetof( FFcodecContext,chroma_elim_threshold),"uint32_t",ADM_param_uint32_t},
 {"lumi_masking",offsetof( FFcodecContext,lumi_masking),"float",ADM_param_float},
 {"is_lumi_masking",offsetof( FFcodecContext,is_lumi_masking),"int32_t",ADM_param_int32_t},
 {"dark_masking",offsetof( FFcodecContext,dark_masking),"float",ADM_param_float},
 {"is_dark_masking",offsetof( FFcodecContext,is_dark_masking),"int32_t",ADM_param_int32_t},
 {"qcompress",offsetof( FFcodecContext,qcompress),"float",ADM_param_float},
 {"qblur",offsetof( FFcodecContext,qblur),"float",ADM_param_float},
 {"minBitrate",offsetof( FFcodecContext,minBitrate),"uint32_t",ADM_param_uint32_t},
 {"maxBitrate",offsetof( FFcodecContext,maxBitrate),"uint32_t",ADM_param_uint32_t},
 {"user_matrix",offsetof( FFcodecContext,user_matrix),"uint32_t",ADM_param_uint32_t},
 {"gop_size",offsetof( FFcodecContext,gop_size),"uint32_t",ADM_param_uint32_t},
 {"interlaced",offsetof( FFcodecContext,interlaced),"uint32_t",ADM_param_uint32_t},
 {"bff",offsetof( FFcodecContext,bff),"uint32_t",ADM_param_uint32_t},
 {"widescreen",offsetof( FFcodecContext,widescreen),"uint32_t",ADM_param_uint32_t},
 {"mb_eval",offsetof( FFcodecContext,mb_eval),"uint32_t",ADM_param_uint32_t},
 {"vratetol",offsetof( FFcodecContext,vratetol),"uint32_t",ADM_param_uint32_t},
 {"is_temporal_cplx_masking",offsetof( FFcodecContext,is_temporal_cplx_masking),"uint32_t",ADM_param_uint32_t},
 {"temporal_cplx_masking",offsetof( FFcodecContext,temporal_cplx_masking),"float",ADM_param_float},
 {"is_spatial_cplx_masking",offsetof( FFcodecContext,is_spatial_cplx_masking),"uint32_t",ADM_param_uint32_t},
 {"spatial_cplx_masking",offsetof( FFcodecContext,spatial_cplx_masking),"float",ADM_param_float},
 {"_NORMALIZE_AQP",offsetof( FFcodecContext,_NORMALIZE_AQP),"uint32_t",ADM_param_uint32_t},
 {"use_xvid_ratecontrol",offsetof( FFcodecContext,use_xvid_ratecontrol),"uint32_t",ADM_param_uint32_t},
 {"bufferSize",offsetof( FFcodecContext,bufferSize),"uint32_t",ADM_param_uint32_t},
 {"override_ratecontrol",offsetof( FFcodecContext,override_ratecontrol),"uint32_t",ADM_param_uint32_t},
 {"dummy",offsetof( FFcodecContext,dummy),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
