// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList artMirror_param[]={
 {"method",offsetof(artMirror,method),"uint32_t",ADM_param_uint32_t},
 {"displacement",offsetof(artMirror,displacement),"float",ADM_param_float},
{NULL,0,NULL}
};
