// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "artMirror.h"
bool  artMirror_jserialize(const char *file, const artMirror *key){
admJson json;
json.addUint32("method",key->method);
json.addFloat("displacement",key->displacement);
return json.dumpToFile(file);
};
bool  artMirror_jdeserialize(const char *file, const ADM_paramList *tmpl,artMirror *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
