// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "lmkv_muxer.h"
bool  lmkv_muxer_jserialize(const char *file, const lmkv_muxer *key){
admJson json;
return json.dumpToFile(file);
};
bool  lmkv_muxer_jdeserialize(const char *file, const ADM_paramList *tmpl,lmkv_muxer *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
