// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList confResampleFps_param[]={
 {"mode",offsetof(confResampleFps,mode),"uint32_t",ADM_param_uint32_t},
 {"newFpsDen",offsetof(confResampleFps,newFpsDen),"uint32_t",ADM_param_uint32_t},
 {"newFpsNum",offsetof(confResampleFps,newFpsNum),"uint32_t",ADM_param_uint32_t},
 {"blend",offsetof(confResampleFps,blend),"bool",ADM_param_bool},
{NULL,0,NULL}
};
