#!/bin/bash
export PKG_CONFIG_PATH=$MINGW/lib/pkgconfig
export PKG_CONFIG_LIBDIR=$MINGW/lib/pkgconfig
export PATH=$MINGW/bin:$PATH
pkg-config --list-all
#export DEBUG="-DVERBOSE=1 -DDEBUG=1  -DCMAKE_BUILD_TYPE=Debug    "
echo "<<<<<<<<<<<<Cross compiling core ($MINGW)>>>>>>>>>>>>>>>>"
cmake   -DCROSS=$MINGW \
	-DTOOLCHAIN_LOCATION=$TOOLCHAIN_LOCATION \
        -DCMAKE_INSTALL_PREFIX=$MINGW/Release \
	-DCMAKE_CROSS_PREFIX=$CROSS_PREFIX \
        -DCMAKE_C_COMPILER:STRING=$CROSS_PREFIX-gcc \
        -DCMAKE_CXX_COMPILER:STRING=$CROSS_PREFIX-g++ \
        -DCMAKE_LINKER:STRING=$CROSS_PREFIX-ld \
        -DCMAKE_AR:STRING=$CROSS_PREFIX-ar \
        -DCMAKE_SYSTEM_NAME:STRING=Windows \
        -DCMAKE_RC_COMPILER:STRING=$MINGW/bin/$CROSS_PREFIX-windres \
        $DEBUG\
        -DAVIDEMUX_TOP_SOURCE_DIR="$TOP"  \
        $TOP/avidemux_core
