// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList ffvtenc_param[]={
 {"profile",offsetof(ffvtenc,profile),"uint32_t",ADM_param_uint32_t},
 {"gopsize",offsetof(ffvtenc,gopsize),"uint32_t",ADM_param_uint32_t},
 {"bframes",offsetof(ffvtenc,bframes),"uint32_t",ADM_param_uint32_t},
 {"bitrate",offsetof(ffvtenc,bitrate),"uint32_t",ADM_param_uint32_t},
 {"max_bitrate",offsetof(ffvtenc,max_bitrate),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
