// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList denoise3dhq_param[]={
 {"mode",offsetof(denoise3dhq,mode),"uint32_t",ADM_param_uint32_t},
 {"luma_spatial",offsetof(denoise3dhq,luma_spatial),"float",ADM_param_float},
 {"chroma_spatial",offsetof(denoise3dhq,chroma_spatial),"float",ADM_param_float},
 {"luma_temporal",offsetof(denoise3dhq,luma_temporal),"float",ADM_param_float},
 {"chroma_temporal",offsetof(denoise3dhq,chroma_temporal),"float",ADM_param_float},
{NULL,0,NULL}
};
