MACRO(checkGettext)
  IF(NOT GETTEXT_CHECKED)
    OPTION(GETTEXT "" ON)

    MESSAGE(STATUS "Checking for gettext")
    MESSAGE(STATUS "********************")
    add_library(adm_gettext INTERFACE)
    find_package(Intl REQUIRED)
    IF(Intl_FOUND)
      SET(HAVE_GETTEXT 1)
      IF(Intl_IS_BUILT_IN)
        MESSAGE(STATUS "libintl is built in")
      ELSE()
        MESSAGE(STATUS "Intl/Gettext version ${Intl_VERSION} found  ( lib = ${Intl_LIBRARIES} incl=${Intl_INCLUDE_DIRS})")
        TARGET_LINK_LIBRARIES( adm_gettext INTERFACE ${Intl_LIBRARIES})
        TARGET_INCLUDE_DIRECTORIES( adm_gettext INTERFACE ${Intl_INCLUDE_DIRS})
      ENDIF()
    ELSE()
      MESSAGE(FATAL_ERROR "Cannot find gettext/intl")
    ENDIF()
    APPEND_SUMMARY_LIST("Miscellaneous" "gettext" "${HAVE_GETTEXT}")
  ENDIF()
ENDMACRO()
