INCLUDE(avidemuxVersion)
IF(WIN32)
  IF(CROSS)
    MESSAGE(STATUS "Using mingw Cross compiler setup")
    INCLUDE(admFFmpegBuild_crossMingw)
  ELSE()
    IF(NOT VS_IMPORT)
      INCLUDE(admFFmpegBuild_vs)
    ELSE()
      INCLUDE(admFFmpegBuild_vs_import)
    ENDIF()
  ENDIF()

ELSE()
  MESSAGE(STATUS "Using native unix setup")
  INCLUDE(admFFmpegBuild_native)
ENDIF()
