// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
uint32_t deintMode;
bool bottomFieldFirst;
bool enableIvtc;
bool resizeToggle;
uint32_t targetWidth;
uint32_t targetHeight;
}vdpauFilterDeint;
