// automatically generated by admSerialization.py do not edit
#ifndef ADM_vdpauFilterDeint_CONF_H
#define ADM_vdpauFilterDeint_CONF_H
typedef struct {
bool resizeToggle;
uint32_t deintMode;
bool enableIvtc;
uint32_t targetWidth;
uint32_t targetHeight;
}vdpauFilterDeint;
#endif
