// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "hue.h"
bool  hue_jserialize(const char *file, const hue *key){
admJson json;
json.addFloat("hue",key->hue);
json.addFloat("saturation",key->saturation);
return json.dumpToFile(file);
};
bool  hue_jdeserialize(const char *file, const ADM_paramList *tmpl,hue *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
