// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "smooth.h"
bool  smooth_jserialize(const char *file, const smooth *key){
admJson json;
json.addUint32("threshold",key->threshold);
json.addBool("showMask",key->showMask);
return json.dumpToFile(file);
};
bool  smooth_jdeserialize(const char *file, const ADM_paramList *tmpl,smooth *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
