// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList opus_encoder_param[]={
 {"bitrate",offsetof(opus_encoder,bitrate),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
