// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList yadif_param[]={
 {"mode",offsetof(yadif,mode),"uint32_t",ADM_param_uint32_t},
 {"order",offsetof(yadif,order),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
