// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList rte_param[]={
 {"angle",offsetof(rte,angle),"float",ADM_param_float},
 {"pad",offsetof(rte,pad),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
