#include "ADM_coreConfig.h"
#define ENABLE_NELLYMOSER_DECODER 1
#define CONFIG_NELLYMOSER_DECODER 1
#define ENABLE_ADPCM_IMA_AMV_DECODER 1
#define CONFIG_ADPCM_IMA_AMV_DECODER 1
#define ENABLE_CINEPAK_DECODER 1
#define CONFIG_CINEPAK_DECODER 1
#define ENABLE_DNXHD_DECODER 1
#define CONFIG_DNXHD_DECODER 1
#define ENABLE_FOURXM_DECODER 1
#define CONFIG_FOURXM_DECODER 1
#define ENABLE_FRAPS_DECODER 1
#define CONFIG_FRAPS_DECODER 1
#define ENABLE_H263_DECODER 1
#define CONFIG_H263_DECODER 1
#define ENABLE_H264_DECODER 1
#define CONFIG_H264_DECODER 1
#define ENABLE_INDEO2_DECODER 1
#define CONFIG_INDEO2_DECODER 1
#define ENABLE_INDEO3_DECODER 1
#define CONFIG_INDEO3_DECODER 1
#define ENABLE_INTERPLAY_VIDEO_DECODER 1
#define CONFIG_INTERPLAY_VIDEO_DECODER 1
#define ENABLE_MPEGVIDEO_DECODER 1
#define CONFIG_MPEGVIDEO_DECODER 1
#define ENABLE_MSVIDEO1_DECODER 1
#define CONFIG_MSVIDEO1_DECODER 1
#define ENABLE_VC1_DECODER 1
#define CONFIG_VC1_DECODER 1
#define ENABLE_VCR1_DECODER 1
#define CONFIG_VCR1_DECODER 1
#define ENABLE_VP5_DECODER 1
#define CONFIG_VP5_DECODER 1
#define ENABLE_VP6_DECODER 1
#define CONFIG_VP6_DECODER 1
#define ENABLE_VP6A_DECODER 1
#define CONFIG_VP6A_DECODER 1
#define ENABLE_VP6F_DECODER 1
#define CONFIG_VP6F_DECODER 1
#define ENABLE_WMV3_DECODER 1
#define CONFIG_WMV3_DECODER 1
#define ENABLE_WMV1_DECODER 1
#define CONFIG_WMV1_DECODER 1
#define ENABLE_WMV2_DECODER 1
#define CONFIG_WMV2_DECODER 1
#define ENABLE_VP3_DECODER 1
#define CONFIG_VP3_DECODER 1
#define ENABLE_MPEG4_DECODER 1
#define CONFIG_MPEG4_DECODER 1
#define ENABLE_MSMPEG4V1_DECODER 1
#define CONFIG_MSMPEG4V1_DECODER 1
#define ENABLE_MSMPEG4V2_DECODER 1
#define CONFIG_MSMPEG4V2_DECODER 1
#define ENABLE_MSMPEG4V3_DECODER 1
#define CONFIG_MSMPEG4V3_DECODER 1
#define ENABLE_MJPEGB_DECODER 1
#define CONFIG_MJPEGB_DECODER 1
#define ENABLE_MJPEG_DECODER 1
#define CONFIG_MJPEG_DECODER 1
#define ENABLE_WMAV2_DECODER 1
#define CONFIG_WMAV2_DECODER 1
#define ENABLE_DVVIDEO_DECODER 1
#define CONFIG_DVVIDEO_DECODER 1
#define ENABLE_HUFFYUV_DECODER 1
#define CONFIG_HUFFYUV_DECODER 1
#define ENABLE_FFVHUFF_DECODER 1
#define CONFIG_FFVHUFF_DECODER 1
#define ENABLE_SVQ3_DECODER 1
#define CONFIG_SVQ3_DECODER 1
#define ENABLE_TSCC_DECODER 1
#define CONFIG_TSCC_DECODER 1
#define ENABLE_QDM2_DECODER 1
#define CONFIG_QDM2_DECODER 1
#define ENABLE_FFV1_DECODER 1
#define CONFIG_FFV1_DECODER 1
#define ENABLE_MPEG1VIDEO_DECODER 1
#define CONFIG_MPEG1VIDEO_DECODER 1
#define ENABLE_MPEG2VIDEO_DECODER 1
#define CONFIG_MPEG2VIDEO_DECODER 1
#define ENABLE_RV10_DECODER 1
#define CONFIG_RV10_DECODER 1
#define ENABLE_RV20_DECODER 1
#define CONFIG_RV20_DECODER 1
#define ENABLE_DVBSUB_DECODER 1
#define CONFIG_DVBSUB_DECODER 1
#define ENABLE_FLV_DECODER 1
#define CONFIG_FLV_DECODER 1
#define ENABLE_SNOW_DECODER 1
#define CONFIG_SNOW_DECODER 1
#define ENABLE_AMV_DECODER 1
#define CONFIG_AMV_DECODER 1
#define ENABLE_H264_VDPAU_DECODER 0
#define ENABLE_EATGQ_DECODER 0
#define ENABLE_PCX_DECODER 0
#define ENABLE_SUNRAST_DECODER 0
#define ENABLE_VB_DECODER 0
#define ENABLE_XSUB_DECODER 0
#define ENABLE_AC3_DECODER 0
#define ENABLE_APE_DECODER 0
#define ENABLE_MPC8_DECODER 0
#define ENABLE_PCM_S16LE_PLANAR_DECODER 0
#define ENABLE_PCM_ZORK_DECODER 0
#define ENABLE_ADPCM_EA_R1_DECODER 0
#define ENABLE_ADPCM_EA_R2_DECODER 0
#define ENABLE_ADPCM_EA_R3_DECODER 0
#define ENABLE_ADPCM_EA_XAS_DECODER 0
#define ENABLE_ADPCM_IMA_EA_EACS_DECODER 0
#define ENABLE_ADPCM_IMA_EA_SEAD_DECODER 0
#define ENABLE_AASC_DECODER 0
#define ENABLE_AVS_DECODER 0
#define ENABLE_BETHSOFTVID_DECODER 0
#define ENABLE_C93_DECODER 0
#define ENABLE_CAVS_DECODER 0
#define ENABLE_CLJR_DECODER 0
#define ENABLE_CSCD_DECODER 0
#define ENABLE_CYUV_DECODER 0
#define ENABLE_DSICINVIDEO_DECODER 0
#define ENABLE_DXA_DECODER 0
#define ENABLE_EIGHTBPS_DECODER 0
#define ENABLE_FLIC_DECODER 0
#define ENABLE_IDCIN_DECODER 0
#define ENABLE_KMVC_DECODER 0
#define ENABLE_LOCO_DECODER 0
#define ENABLE_MDEC_DECODER 0
#define ENABLE_MMVIDEO_DECODER 0
#define ENABLE_MPEG_XVMC_DECODER 0
#define ENABLE_MSRLE_DECODER 0
#define ENABLE_MSZH_DECODER 0
#define ENABLE_NUV_DECODER 0
#define ENABLE_PTX_DECODER 0
#define ENABLE_QDRAW_DECODER 0
#define ENABLE_QPEG_DECODER 0
#define ENABLE_RPZA_DECODER 0
#define ENABLE_SMACKER_DECODER 0
#define ENABLE_SMC_DECODER 0
#define ENABLE_SP5X_DECODER 0
#define ENABLE_THEORA_DECODER 0
#define ENABLE_THP_DECODER 0
#define ENABLE_TIERTEXSEQVIDEO_DECODER 0
#define ENABLE_TRUEMOTION1_DECODER 0
#define ENABLE_TRUEMOTION2_DECODER 0
#define ENABLE_TXD_DECODER 0
#define ENABLE_ULTI_DECODER 0
#define ENABLE_VMDVIDEO_DECODER 0
#define ENABLE_VMNC_DECODER 0
#define ENABLE_VQA_DECODER 0
#define ENABLE_WNV1_DECODER 0
#define ENABLE_XAN_WC3_DECODER 0
#define ENABLE_XL_DECODER 0
#define ENABLE_MPEG4AAC_DECODER 0
#define ENABLE_ALAC_DECODER 0
#define ENABLE_ATRAC3_DECODER 0
#define ENABLE_COOK_DECODER 0
#define ENABLE_DCA_DECODER 0
#define ENABLE_DSICINAUDIO_DECODER 0
#define ENABLE_IMC_DECODER 0
#define ENABLE_LIBA52_DECODER 0
#define ENABLE_LIBFAAD_DECODER 0
#define ENABLE_MACE3_DECODER 0
#define ENABLE_MACE6_DECODER 0
#define ENABLE_MP3_DECODER 0
#define ENABLE_MP3ADU_DECODER 0
#define ENABLE_MP3ON4_DECODER 0
#define ENABLE_MPC7_DECODER 0
#define ENABLE_RA_144_DECODER 0
#define ENABLE_RA_288_DECODER 0
#define ENABLE_SHORTEN_DECODER 0
#define ENABLE_SMACKAUD_DECODER 0
#define ENABLE_TRUESPEECH_DECODER 0
#define ENABLE_TTA_DECODER 0
#define ENABLE_VMDAUDIO_DECODER 0
#define ENABLE_WAVPACK_DECODER 0
#define ENABLE_WS_SND1_DECODER 0
#define ENABLE_INTERPLAY_DPCM_DECODER 0
#define ENABLE_SOL_DPCM_DECODER 0
#define ENABLE_XAN_DPCM_DECODER 0
#define ENABLE_ADPCM_THP_DECODER 0
#define ENABLE_ASV1_DECODER 0
#define ENABLE_ASV2_DECODER 0
#define ENABLE_BMP_DECODER 0
#define ENABLE_FLASHSV_DECODER 0
#define ENABLE_GIF_DECODER 0
#define ENABLE_H261_DECODER 0
#define ENABLE_H263I_DECODER 0
#define ENABLE_JPEGLS_DECODER 0
#define ENABLE_PNG_DECODER 0
#define ENABLE_QTRLE_DECODER 0
#define ENABLE_RAWVIDEO_DECODER 0
#define ENABLE_ROQ_DECODER 0
#define ENABLE_SGI_DECODER 0
#define ENABLE_SVQ1_DECODER 0
#define ENABLE_TARGA_DECODER 0
#define ENABLE_TIFF_DECODER 0
#define ENABLE_ZLIB_DECODER 0
#define ENABLE_ZMBV_DECODER 0
#define ENABLE_FLAC_DECODER 0
#define ENABLE_LIBAMR_NB_DECODER 0
#define ENABLE_LIBAMR_WB_DECODER 0
#define ENABLE_LIBGSM_DECODER 0
#define ENABLE_LIBGSM_MS_DECODER 0
#define ENABLE_MP2_DECODER 0
#define ENABLE_SONIC_DECODER 0
#define ENABLE_VORBIS_DECODER 0
#define ENABLE_WMAV1_DECODER 0
#define ENABLE_PCM_ALAW_DECODER 0
#define ENABLE_PCM_MULAW_DECODER 0
#define ENABLE_PCM_S8_DECODER 0
#define ENABLE_PCM_S16BE_DECODER 0
#define ENABLE_PCM_S16LE_DECODER 0
#define ENABLE_PCM_S24BE_DECODER 0
#define ENABLE_PCM_S24DAUD_DECODER 0
#define ENABLE_PCM_S24LE_DECODER 0
#define ENABLE_PCM_S32BE_DECODER 0
#define ENABLE_PCM_S32LE_DECODER 0
#define ENABLE_PCM_U8_DECODER 0
#define ENABLE_PCM_U16BE_DECODER 0
#define ENABLE_PCM_U16LE_DECODER 0
#define ENABLE_PCM_U24BE_DECODER 0
#define ENABLE_PCM_U24LE_DECODER 0
#define ENABLE_PCM_U32BE_DECODER 0
#define ENABLE_PCM_U32LE_DECODER 0
#define ENABLE_ROQ_DPCM_DECODER 0
#define ENABLE_ADPCM_4XM_DECODER 0
#define ENABLE_ADPCM_ADX_DECODER 0
#define ENABLE_ADPCM_CT_DECODER 0
#define ENABLE_ADPCM_EA_DECODER 0
#define ENABLE_ADPCM_G726_DECODER 0
#define ENABLE_ADPCM_IMA_DK3_DECODER 0
#define ENABLE_ADPCM_IMA_DK4_DECODER 0
#define ENABLE_ADPCM_IMA_QT_DECODER 0
#define ENABLE_ADPCM_IMA_SMJPEG_DECODER 0
#define ENABLE_ADPCM_IMA_WAV_DECODER 0
#define ENABLE_ADPCM_IMA_WS_DECODER 0
#define ENABLE_ADPCM_MS_DECODER 0
#define ENABLE_ADPCM_SBPRO_2_DECODER 0
#define ENABLE_ADPCM_SBPRO_3_DECODER 0
#define ENABLE_ADPCM_SBPRO_4_DECODER 0
#define ENABLE_ADPCM_SWF_DECODER 0
#define ENABLE_ADPCM_XA_DECODER 0
#define ENABLE_ADPCM_YAMAHA_DECODER 0
#define ENABLE_DVDSUB_DECODER 0
#define ENABLE_LIBVORBIS_DECODER 0
#define ENABLE_H263_PARSER 1
#define ENABLE_H264_PARSER 1
#define ENABLE_MPEG4VIDEO_PARSER 1
#define ENABLE_AAC_PARSER 0
#define ENABLE_AC3_PARSER 0
#define ENABLE_CAVSVIDEO_PARSER 0
#define ENABLE_DCA_PARSER 0
#define ENABLE_DVBSUB_PARSER 0
#define ENABLE_DVDSUB_PARSER 0
#define ENABLE_H261_PARSER 0
#define ENABLE_MJPEG_PARSER 0
#define ENABLE_MPEGAUDIO_PARSER 0
#define ENABLE_MPEGVIDEO_PARSER 0
#define ENABLE_PNM_PARSER 0
#define ENABLE_VC1_PARSER 0
#define ENABLE_MJPEG_ENCODER 1
#define CONFIG_MJPEG_ENCODER 1
#define ENABLE_MSMPEG4V3_ENCODER 1
#define CONFIG_MSMPEG4V3_ENCODER 1
#define ENABLE_H263P_ENCODER 1
#define CONFIG_H263P_ENCODER 1
#define ENABLE_AC3_ENCODER 1
#define CONFIG_AC3_ENCODER 1
#define ENABLE_FFV1_ENCODER 1
#define CONFIG_FFV1_ENCODER 1
#define ENABLE_FLV1_ENCODER 1
#define CONFIG_FLV1_ENCODER 1
#define ENABLE_FFVHUFF_ENCODER 1
#define CONFIG_FFVHUFF_ENCODER 1
#define ENABLE_H263_ENCODER 1
#define CONFIG_H263_ENCODER 1
#define ENABLE_MPEG1VIDEO_ENCODER 1
#define CONFIG_MPEG1VIDEO_ENCODER 1
#define ENABLE_MPEG2VIDEO_ENCODER 1
#define CONFIG_MPEG2VIDEO_ENCODER 1
#define ENABLE_MPEG4_ENCODER 1
#define CONFIG_MPEG4_ENCODER 1
#define ENABLE_FLV_ENCODER 1
#define CONFIG_FLV_ENCODER 1
#define ENABLE_MP2_ENCODER 1
#define CONFIG_MP2_ENCODER 1
#define ENABLE_DVVIDEO_ENCODER 1
#define CONFIG_DVVIDEO_ENCODER 1
#define ENABLE_HUFFYUV_ENCODER 1
#define CONFIG_HUFFYUV_ENCODER 1
#define ENABLE_DVBSUB_ENCODER 1
#define CONFIG_DVBSUB_ENCODER 1
#define ENABLE_SNOW_ENCODER 1
#define CONFIG_SNOW_ENCODER 1
#define ENABLE_DNXHD_ENCODER 0
#define ENABLE_PCM_ZORK_ENCODER 0
#define ENABLE_ADPCM_IMA_AMV_ENCODER 0
#define ENABLE_LIBX264_ENCODER 0
#define ENABLE_LIBXVID_ENCODER 0
#define ENABLE_LJPEG_ENCODER 0
#define ENABLE_PAM_ENCODER 0
#define ENABLE_PBM_ENCODER 0
#define ENABLE_PGM_ENCODER 0
#define ENABLE_PGMYUV_ENCODER 0
#define ENABLE_PPM_ENCODER 0
#define ENABLE_LIBFAAC_ENCODER 0
#define ENABLE_LIBMP3LAME_ENCODER 0
#define ENABLE_LIBTHEORA_ENCODER 0
#define ENABLE_SONIC_LS_ENCODER 0
#define ENABLE_ASV1_ENCODER 0
#define ENABLE_ASV2_ENCODER 0
#define ENABLE_BMP_ENCODER 0
#define ENABLE_FLASHSV_ENCODER 0
#define ENABLE_GIF_ENCODER 0
#define ENABLE_H261_ENCODER 0
#define ENABLE_JPEGLS_ENCODER 0
#define ENABLE_MSMPEG4V1_ENCODER 0
#define ENABLE_MSMPEG4V2_ENCODER 0
#define ENABLE_PNG_ENCODER 0
#define ENABLE_QTRLE_ENCODER 0
#define ENABLE_RAWVIDEO_ENCODER 0
#define ENABLE_ROQ_ENCODER 0
#define ENABLE_RV10_ENCODER 0
#define ENABLE_RV20_ENCODER 0
#define ENABLE_SGI_ENCODER 0
#define ENABLE_SVQ1_ENCODER 0
#define ENABLE_TARGA_ENCODER 0
#define ENABLE_TIFF_ENCODER 0
#define ENABLE_WMV1_ENCODER 0
#define ENABLE_WMV2_ENCODER 0
#define ENABLE_ZLIB_ENCODER 0
#define ENABLE_ZMBV_ENCODER 0
#define ENABLE_FLAC_ENCODER 0
#define ENABLE_LIBAMR_NB_ENCODER 0
#define ENABLE_LIBAMR_WB_ENCODER 0
#define ENABLE_LIBGSM_ENCODER 0
#define ENABLE_LIBGSM_MS_ENCODER 0
#define ENABLE_SONIC_ENCODER 0
#define ENABLE_VORBIS_ENCODER 0
#define ENABLE_WMAV1_ENCODER 0
#define ENABLE_WMAV2_ENCODER 0
#define ENABLE_PCM_ALAW_ENCODER 0
#define ENABLE_PCM_MULAW_ENCODER 0
#define ENABLE_PCM_S8_ENCODER 0
#define ENABLE_PCM_S16BE_ENCODER 0
#define ENABLE_PCM_S16LE_ENCODER 0
#define ENABLE_PCM_S24BE_ENCODER 0
#define ENABLE_PCM_S24DAUD_ENCODER 0
#define ENABLE_PCM_S24LE_ENCODER 0
#define ENABLE_PCM_S32BE_ENCODER 0
#define ENABLE_PCM_S32LE_ENCODER 0
#define ENABLE_PCM_U8_ENCODER 0
#define ENABLE_PCM_U16BE_ENCODER 0
#define ENABLE_PCM_U16LE_ENCODER 0
#define ENABLE_PCM_U24BE_ENCODER 0
#define ENABLE_PCM_U24LE_ENCODER 0
#define ENABLE_PCM_U32BE_ENCODER 0
#define ENABLE_PCM_U32LE_ENCODER 0
#define ENABLE_ROQ_DPCM_ENCODER 0
#define ENABLE_ADPCM_4XM_ENCODER 0
#define ENABLE_ADPCM_ADX_ENCODER 0
#define ENABLE_ADPCM_CT_ENCODER 0
#define ENABLE_ADPCM_EA_ENCODER 0
#define ENABLE_ADPCM_G726_ENCODER 0
#define ENABLE_ADPCM_IMA_DK3_ENCODER 0
#define ENABLE_ADPCM_IMA_DK4_ENCODER 0
#define ENABLE_ADPCM_IMA_QT_ENCODER 0
#define ENABLE_ADPCM_IMA_SMJPEG_ENCODER 0
#define ENABLE_ADPCM_IMA_WAV_ENCODER 0
#define ENABLE_ADPCM_IMA_WS_ENCODER 0
#define ENABLE_ADPCM_MS_ENCODER 0
#define ENABLE_ADPCM_SBPRO_2_ENCODER 0
#define ENABLE_ADPCM_SBPRO_3_ENCODER 0
#define ENABLE_ADPCM_SBPRO_4_ENCODER 0
#define ENABLE_ADPCM_SWF_ENCODER 0
#define ENABLE_ADPCM_XA_ENCODER 0
#define ENABLE_ADPCM_YAMAHA_ENCODER 0
#define ENABLE_DVDSUB_ENCODER 0
#define ENABLE_LIBVORBIS_ENCODER 0
#define ENABLE_MP3_HEADER_COMPRESS_BSF 0
#define ENABLE_IMX_DUMP_HEADER_BSF 0
#define ENABLE_DUMP_EXTRADATA_BSF 0
#define ENABLE_REMOVE_EXTRADATA_BSF 0
#define ENABLE_NOISE_BSF 0
#define ENABLE_MP3_HEADER_DECOMPRESS_BSF 0
#define ENABLE_MJPEGA_DUMP_HEADER_BSF 0
#define ENABLE_H264_MP4TOANNEXB_BSF 0
#define ENABLE_MOV2TEXTSUB_BSF 0
#define ENABLE_TEXT2MOVSUB_BSF 0
#define CONFIG_MUXERS 1
#define CONFIG_MOV_MUXER 1
#define CONFIG_MP4_MUXER 1
#define CONFIG_PSP_MUXER 1
#define CONFIG_TG2_MUXER 1
#define CONFIG_TGP_MUXER 1
#define CONFIG_ENCODERS 1
#define CONFIG_DVVIDEO_ENCODER 1
#define CONFIG_SNOW_ENCODER 1
#define CONFIG_DECODERS 1
#define CONFIG_DVVIDEO_DECODER 1
#define CONFIG_H263_DECODER 1
#define CONFIG_MPEG4_DECODER 1
#define CONFIG_SNOW_DECODER 1
#define CONFIG_VC1_DECODER 1
#define CONFIG_WMV2_DECODER 1
#define CONFIG_WMV3_DECODER 1
#define CONFIG_MPEGAUDIO_HP 1
#define CONFIG_ZLIB 1
#define CONFIG_GPL 1
#define ENABLE_ARMV4L 0
#define ENABLE_MLIB 0
#define ENABLE_SPARC 0
#define ENABLE_ALPHA 0
#define ENABLE_MMI 0
#define ENABLE_SH4 0
#define ENABLE_BFIN 0
#define ENABLE_SMALL 0
#define ENABLE_MLP_PARSER 0
//****************** SYSTEM *******************
#ifdef __APPLE__
#	define CONFIG_DARWIN 1
#endif
#if defined(ADM_CPU_X86_32)
#	define ARCH_X86 1
#	define ARCH_X86_32 1
#elif defined(ADM_CPU_X86_64)
#	define ARCH_X86 1
#	define ARCH_X86_64 1
#elif defined(ADM_CPU_PPC)
#	define ARCH_POWERPC 1
#ifdef ADM_CPU_ALTIVEC
#	define HAVE_ALTIVEC 1
#ifndef __APPLE__
#	define HAVE_ALTIVEC_H 1
#endif	// __APPLE__
#endif	// ADM_CPU_ALTIVEC
#ifdef ADM_CPU_DCBZL
#	define HAVE_DCBZL 1
#endif	// ADM_CPU_DCBZL
#endif	// ADM_CPU_X86_32
#ifndef ADM_MINIMAL_INCLUDE
#if defined(ADM_CPU_X86_32) && defined(ADM_CPU_MMX2)
#	define HAVE_MMX2 1
#endif
#ifdef ADM_CPU_SSSE3
#	define HAVE_SSSE3 1
#endif
#endif //ADM_MINIMAL_INCLUDE
#ifdef ARCH_POWERPC
#	define ENABLE_POWERPC 1
#else
#	define ENABLE_POWERPC 0
#endif
#ifdef ARCH_X86
#	define ENABLE_BSWAP 1
#ifndef ADM_MINIMAL_INCLUDE
#	define HAVE_MMX 1
#	define ENABLE_MMX 1
#endif //ADM_MINIMAL_INCLUDE
#	define HAVE_FAST_UNALIGNED 1
#	define HAVE_EBP_AVAILABLE 1
#	define HAVE_EBX_AVAILABLE 1
#else
#	define ENABLE_MMX 0
#endif
#ifdef ARCH_X86_64
#	define HAVE_FAST_64BIT 1
#endif
#ifdef ADM_BIG_ENDIAN
#	define WORDS_BIGENDIAN 1
#endif
#define ENABLE_YASM      0
#define ENABLE_ARM      0
#define ENABLE_PPC      0
#define ENABLE_THREADS 1
#define ENABLE_ENCODERS 1
#define CONFIG_MUXERS 1
#define CONFIG_DEMUXERS 1
#define ENABLE_VIS 0
#define ENABLE_GRAY 0
#define HAVE_LRINTF 1
#define HAVE_LLRINT 1
#define HAVE_LRINT 1
#define HAVE_ROUND 1
#define HAVE_ROUNDF 1
#define HAVE_THREADS 1
#define RUNTIME_CPUDETECT 1
#ifdef __MINGW32__
#define EXTERN_PREFIX "_"
#else // __MINGW32__
#define EXTERN_PREFIX
#endif // __MINGW32__
#define restrict __restrict__
