// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList configuration_param[]={
 {"start",offsetof(configuration,start),"uint32_t",ADM_param_uint32_t},
 {"duration",offsetof(configuration,duration),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
