// automatically generated by pref_gen.py, do not edit!
#if 0
typedef struct
{
   const char *name;
   TYPE  type;
   const char *defaultValue;
   const char *min;
   const char *max;
   char *Value;
}optionDesc;
#endif 
static optionDesc myOptions[]={
{ FEATURES_SWAP_IF_A_GREATER_THAN_B,"features.swap_if_A_greater_than_B",	ADM_param_bool    	,"1",	"0",	"1",	NULL},
{ FEATURES_SAVEPREFSONEXIT,"features.saveprefsonexit",	ADM_param_bool    	,"1",	"0",	"1",	NULL},
{ FEATURES_IGNORESAVEDMARKERS,"features.ignoresavedmarkers",	ADM_param_bool    	,"0",	"0",	"1",	NULL},
{ FEATURES_USE_ODML,"features.use_odml",	ADM_param_uint32_t	,"0",	"0",	"1",	NULL},
{ FEATURES_USE_SYSTRAY,"features.use_systray",	ADM_param_uint32_t	,"0",	"0",	"1",	NULL},
{ FEATURES_REUSE_2PASS_LOG,"features.reuse_2pass_log",	ADM_param_bool    	,"0",	"0",	"1",	NULL},
{ FEATURES_AUDIOBAR_USES_MASTER,"features.audiobar_uses_master",	ADM_param_bool    	,"0",	"0",	"1",	NULL},
{ FEATURES_THREADING_LAVC,"features.threading_lavc",	ADM_param_uint32_t	,"0",	"0",	"32",	NULL},
{ FEATURES_CPU_CAPS,"features.cpu_caps",	ADM_param_uint32_t	,"4294967295",	"0",	"4294967295",	NULL},
{ FEATURES_MPEG_NO_LIMIT,"features.mpeg_no_limit",	ADM_param_uint32_t	,"0",	"0",	"1",	NULL},
{ FEATURES_ALTERNATE_MP3_TAG,"features.alternate_mp3_tag",	ADM_param_bool    	,"1",	"0",	"1",	NULL},
{ FEATURES_VDPAU,"features.vdpau",	ADM_param_bool    	,"0",	"0",	"1",	NULL},
{ LASTFILES_LASTDIR_READ,"lastfiles.lastdir_read",	ADM_param_string  	,"",	NULL,	NULL,	NULL},
{ LASTFILES_LASTDIR_WRITE,"lastfiles.lastdir_write",	ADM_param_string  	,"",	NULL,	NULL,	NULL},
{ LASTFILES_FILE1,"lastfiles.file1",	ADM_param_string  	,"",	NULL,	NULL,	NULL},
{ LASTFILES_FILE2,"lastfiles.file2",	ADM_param_string  	,"",	NULL,	NULL,	NULL},
{ LASTFILES_FILE3,"lastfiles.file3",	ADM_param_string  	,"",	NULL,	NULL,	NULL},
{ LASTFILES_FILE4,"lastfiles.file4",	ADM_param_string  	,"",	NULL,	NULL,	NULL},
{ MESSAGE_LEVEL,"message_level",	ADM_param_uint32_t	,"2",	"0",	"2",	NULL},
{ AUDIO_DEVICE_AUDIODEVICE,"audio_device.audiodevice",	ADM_param_string  	,"ALSA",	NULL,	NULL,	NULL},
{ AUDIO_DEVICE_ALSA_DEVICE,"audio_device.alsa_device",	ADM_param_string  	,"dmix",	NULL,	NULL,	NULL},
{ VIDEODEVICE,"videodevice",	ADM_param_uint32_t	,"0",	"0",	"10",	NULL},
{ PRIORITY_ENCODING,"priority.encoding",	ADM_param_uint32_t	,"3",	"0",	"4",	NULL},
{ PRIORITY_INDEXING,"priority.indexing",	ADM_param_uint32_t	,"3",	"0",	"4",	NULL},
{ PRIORITY_PLAYBACK,"priority.playback",	ADM_param_uint32_t	,"0",	"0",	"4",	NULL},
{ DEFAULT_POSTPROC_TYPE,"Default.postproc_type",	ADM_param_uint32_t	,"3",	"0",	"7",	NULL},
{ DEFAULT_POSTPROC_VALUE,"Default.postproc_value",	ADM_param_uint32_t	,"3",	"0",	"5",	NULL},
{ DEFAULT_DOWNMIXING,"Default.downmixing",	ADM_param_uint32_t	,"2",	"0",	"2",	NULL},
{ MPEGSPLIT_AUTOSPLIT,"mpegsplit_autosplit",	ADM_param_uint32_t	,"790",	"400",	"5000",	NULL},
};

