// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList zoom_param[]={
 {"top",offsetof(zoom,top),"uint32_t",ADM_param_uint32_t},
 {"bottom",offsetof(zoom,bottom),"uint32_t",ADM_param_uint32_t},
 {"left",offsetof(zoom,left),"uint32_t",ADM_param_uint32_t},
 {"right",offsetof(zoom,right),"uint32_t",ADM_param_uint32_t},
 {"ar_select",offsetof(zoom,ar_select),"uint32_t",ADM_param_uint32_t},
 {"algo",offsetof(zoom,algo),"uint32_t",ADM_param_uint32_t},
 {"pad",offsetof(zoom,pad),"uint32_t",ADM_param_uint32_t},
 {"tolerance",offsetof(zoom,tolerance),"float",ADM_param_float},
{NULL,0,NULL}
};
