// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
std::string wine_app;
std::string avs_script;
std::string avs_loader;
uint32_t pipe_timeout;
uint32_t debug_msg;
uint32_t script_mtime;
uint32_t script_ctime;
}avsfilter_config;
