// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList avsfilter_config_param[]={
 {"wine_app",offsetof(avsfilter_config,wine_app),"std::string",ADM_param_stdstring},
 {"avs_script",offsetof(avsfilter_config,avs_script),"std::string",ADM_param_stdstring},
 {"avs_loader",offsetof(avsfilter_config,avs_loader),"std::string",ADM_param_stdstring},
 {"pipe_timeout",offsetof(avsfilter_config,pipe_timeout),"uint32_t",ADM_param_uint32_t},
 {"debug_msg",offsetof(avsfilter_config,debug_msg),"uint32_t",ADM_param_uint32_t},
 {"script_mtime",offsetof(avsfilter_config,script_mtime),"uint32_t",ADM_param_uint32_t},
 {"script_ctime",offsetof(avsfilter_config,script_ctime),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
