// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "artCharcoal.h"
bool  artCharcoal_jserialize(const char *file, const artCharcoal *key){
admJson json;
json.addInt32("scatterX",key->scatterX);
json.addInt32("scatterY",key->scatterY);
json.addFloat("intensity",key->intensity);
json.addFloat("color",key->color);
json.addBool("invert",key->invert);
return json.dumpToFile(file);
};
bool  artCharcoal_jdeserialize(const char *file, const ADM_paramList *tmpl,artCharcoal *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
