// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "logo.h"
bool  logo_jserialize(const char *file, const logo *key){
admJson json;
json.addUint32("x",key->x);
json.addUint32("y",key->y);
json.addUint32("alpha",key->alpha);
json.addString("logoImageFile",key->logoImageFile);
json.addUint32("fade",key->fade);
json.addFloat("scale",key->scale);
return json.dumpToFile(file);
};
bool  logo_jdeserialize(const char *file, const ADM_paramList *tmpl,logo *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
