// automatically generated by admSerialization.py, do not edit!
// automatically generated by admSerialization.py do not edit
#ifndef ADM_mkv_muxer_CONF_H
#define ADM_mkv_muxer_CONF_H
typedef struct {
bool forceDisplayWidth;
uint32_t displayWidth;
}mkv_muxer;
#endif
