// automatically generated by admSerialization.py, do not edit!
// automatically generated by admSerialization.py do not edit
#ifndef ADM_kdeint_CONF_H
#define ADM_kdeint_CONF_H
typedef struct {
uint32_t order;
uint32_t threshold;
uint32_t sharp;
uint32_t twoway;
uint32_t map;
}kdeint;
#endif
