// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList kdeint_param[]={
 {"order",offsetof(kdeint,order),"uint32_t",ADM_param_uint32_t},
 {"threshold",offsetof(kdeint,threshold),"uint32_t",ADM_param_uint32_t},
 {"sharp",offsetof(kdeint,sharp),"bool",ADM_param_bool},
 {"twoway",offsetof(kdeint,twoway),"bool",ADM_param_bool},
 {"map",offsetof(kdeint,map),"bool",ADM_param_bool},
{NULL,0,NULL}
};
