// automatically generated by admSerialization.py do not edit
#ifndef ADM_kdeint_CONF_H
#define ADM_kdeint_CONF_H
typedef struct {
uint32_t order;
uint32_t threshold;
bool sharp;
bool twoway;
bool map;
}kdeint;
#endif
