// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList eq2_param[]={
 {"contrast",offsetof(eq2,contrast),"float",ADM_param_float},
 {"brightness",offsetof(eq2,brightness),"float",ADM_param_float},
 {"saturation",offsetof(eq2,saturation),"float",ADM_param_float},
 {"gamma",offsetof(eq2,gamma),"float",ADM_param_float},
 {"gamma_weight",offsetof(eq2,gamma_weight),"float",ADM_param_float},
 {"rgamma",offsetof(eq2,rgamma),"float",ADM_param_float},
 {"bgamma",offsetof(eq2,bgamma),"float",ADM_param_float},
 {"ggamma",offsetof(eq2,ggamma),"float",ADM_param_float},
{NULL,0,NULL}
};
