// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "eq2.h"
bool  eq2_jserialize(const char *file, const eq2 *key){
admJson json;
json.addFloat("contrast",key->contrast);
json.addFloat("brightness",key->brightness);
json.addFloat("saturation",key->saturation);
json.addFloat("gamma",key->gamma);
json.addFloat("gamma_weight",key->gamma_weight);
json.addFloat("rgamma",key->rgamma);
json.addFloat("bgamma",key->bgamma);
json.addFloat("ggamma",key->ggamma);
return json.dumpToFile(file);
};
bool  eq2_jdeserialize(const char *file, const ADM_paramList *tmpl,eq2 *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
