%{
#include "stdio.h"
#include "ADM_jsAvidemux.h"
void jsAvidemux(void)
{
        printf("Constructor invoked\n");
}
%}
        /*            JSFUNC      C FUNC  PARAM     */
class adm
{
        function int loadVideo      : jsLoadVideo (cstring ) <static>;
        function int clearSegments  : jsClearSegments () <static>;
        function int appendVideo    : jsAppendVideo (cstring ) <static>;
        function int addSegment     : jsAddSegment (int ,double , double ) <static>;
        function int setPostProc    : jsSetPostProc (int ,int , int ) <static>;
        function int audioReset     : jsAudioReset () <static>;
        function int audioMixer     : jsAudioMixer (cstring ) <static>;
        /*            JSFUNC                 C FUNC           PARAM     */
/* Override as jsapigen cannot handle multiple args the way we need it to */
        function int videoCodec_ignore     : jsVideoCodec(cstring,cstring[])   <static>;
        function int addVideoFilter_ignore : jsVideoFilter(cstring,cstring[])   <static>;
        function int audioCodec_ignore     : jsAudioCodec(cstring,cstring[])   <static>;
        function int setContainer_ignore   : jsSetContainer(cstring,cstring[])   <static>;
/* Properties */
        property double markerA            : jsGetMarkerA,jsSetMarkerA <static>;
        property double markerB            : jsGetMarkerB,jsSetMarkerB <static>;
        property int    audioResample      : jsGetResample,jsSetResample <static>;
        construct                          : jsAvidemux  ( ) <static>     ; 
};

%<

JSObject *jsAvidemuxInit(JSContext *cx,JSObject *obj)
{
          if (JS_DefineFunctions(cx, obj, jj_static_fs) != JS_TRUE) 
          {
                return NULL;
          }
          return jjadm_init(cx,obj);
}

JSFunctionSpec  *jsGetAdmFunctions(void)
{
        return jjadm_static_fs;
}

%>
