/*
###############################################################
       return JS function     C Function  params
###############################################################
*/
function bool admTestFacInt     :  jsTestFacInt     (void  ) <static>;
function bool admTestFacFloat   :  jsTestFacFloat   (void  ) <static>;
function bool admTestFacToggle  :  jsTestFacToggle  (void  ) <static>;
function bool admTestFacMenu    :  jsTestFacMenu    (void  ) <static>;
function bool admTestFacFile    :  jsTestFacFile    (void  ) <static>;
function bool admTestFacBitrate :  jsTestFacBitrate (void  ) <static>;
function bool admTestFacBar     :  jsTestFacBar     (void  ) <static>;
function bool admTestFacRoText  :  jsTestFacRoText  (void  ) <static>;
function bool admTestFacText    :  jsTestFacText    (void  ) <static>;
function bool admTestFacTab     :  jsTestFacTab     (void  ) <static>;
function bool admTestFrame      :  jsTestFacFrame   (void  ) <static>;
function bool admTestHex        :  jsTestFacHex     (void  ) <static>;
function bool admTestDirSel     :  jsTestFacDirSel  (void  ) <static>;
function bool admTestButton     :  jsTestFacButton  (void  ) <static>;
function bool admTestMatrix     :  jsTestFacMatrix  (void  ) <static>;
function bool admTestNotch      :  jsTestFacNotch   (void  ) <static>;
function bool admTestThreadCount:  jsTestFacThreadCount   (void  ) <static>;
function bool admTestSlider     :  jsTestFacSlider  (void  ) <static>;
function void admTestCrash      :  jsTestCrash      (void  ) <static>;
function void admTestAssert     :  jsTestAssert     (void  ) <static>;

%<
JSFunctionSpec  *jsGetTestFunctions(void)
{
        return jj_static_fs;
}

%>

