/*
###############################################################
       return JS function     CM Function  params
###############################################################
*/
function void admPopupError : jsPopupError   (cstring  ) <static>;
function void admpPopupInfo : jsPopupInfo    (cstring  ) <static>;
function void admPrint      : jsPrint        (cstring  ) <static>;
function void print         : jsPrint2       (cstring  ) <static>;
function void help          : jsHelp         (cstring  ) <static>;

%<
JSFunctionSpec  *jsGetIfFunctions(void)
{
        return jj_static_fs;
}

%>
