/*
--- DO NOT EDIT THIS FILE !!! ---

This file has been generated automatically with 'jsapigen'.

jsapigen is a glue-code generator for SpiderMonkey. It is distributed
under the conditions of version 3 of the GNU General Public License.
Please have a look at http://jsapigen.sourceforge.net.

This file is NOT part of jsapigen and is NOT necessarily covered by
jsapigen's license. For licensing information regarding this file,
please refer to the software package which it is part of.

*/

#include "stdio.h"
#include "ADM_jsAvidemux.h"
void jsAvidemux(void)
{
        printf("Constructor invoked\n");
}

#include <string.h>
#include <wchar.h>
#include <jsapi.h>
#ifndef JS_THREADSAFE
#if JS_VERSION <= 170
#define jsrefcount int
#define JS_BeginRequest(cx)
#define JS_EndRequest(cx)
#define JS_SuspendRequest(cx)
#define JS_ResumeRequest(cx, saveDepth)
#endif
#endif
#ifndef JS_FS
#define JS_FS(name, call, nargs, flags, extra) {name, call, nargs, flags, extra}
#endif
#ifndef JS_FS_END
#define JS_FS_END {NULL, NULL, 0, 0, 0}
#endif
static JSPropertySpec jj_static_ps[] = {
    {NULL, 0, 0, NULL, NULL}
};
static JSPropertySpec jj_ps[] = {
    {NULL, 0, 0, NULL, NULL}
};
static JSFunctionSpec jj_static_fs[] = {
    JS_FS_END
};
static JSFunctionSpec jj_fs[] = {
    JS_FS_END
};
static JSBool
jjadmloadVideo(JSContext *cx, JSObject *obj, uintN argc, jsval *argv, jsval *rval)
{
    JSObject *var2;
    char *var7;
    int var3;
    int var6;
    int var8;
    jsval var9;
    JSString *var10;
    jsval var22;
    size_t var11;
    size_t var12;
    int var14;
    jschar *var13;
    jsval var23;
    jsval var15;
    JSBool var1;
    var2 = NULL;
    var7 = NULL;
    var3 = 0;
    var6 = 0;
    var8 = 0;
    var9 = JSVAL_NULL;
    var10 = NULL;
    var22 = JSVAL_NULL;
    var11 = 0;
    var12 = 0;
    var14 = 0;
    var13 = NULL;
    var23 = JSVAL_NULL;
    var15 = JSVAL_NULL;
    var1 = JS_FALSE;
    var2 = obj;
    var6 = argc;
    var8 = 0;
    var8 = var8 < var6;
    if (var8) {
    var9 = argv[0];
    var10 = JS_ValueToString(cx, var9);
    if (!var10) {
        goto do_return;
    }
    var22 = STRING_TO_JSVAL(var10);
    argv[argc+0] = var22;
    var11 = JS_GetStringLength(var10);
    var12 = 1;
    var12 += var11;
    var7 = JS_malloc(cx, var12);
    if (!var7) {
        goto do_return;
    }
    var14 = 1;
    var13 = JS_GetStringChars(var10);
    var23 = STRING_TO_JSVAL(var10);
    argv[argc+1] = var23;
    {
        size_t i;
        for (i = 0; i < var11; ++i) {
            var7[i] = wctob(var13[i]);
        }
        var7[var11] = '\0';
    }
    }
    var3 = jsLoadVideo(var7);
    if (JS_NewNumberValue(cx, var3, &var15) != JS_TRUE) {
        goto do_return;
    }
    argv[argc+2] = var15;
    if (rval) {
        *rval = var15;
    }
    var1 = JS_TRUE;
    do_return:
    if (var14) {
        JS_free(cx, var7);
        var7 = NULL;
        var14 = 0;
    }
    return var1;
}
static JSBool
jjadm__construct__(JSContext *cx, JSObject *obj, uintN argc, jsval *argv, jsval *rval)
{
    JSObject *var17;
    int var21;
    JSBool var16;
    var17 = NULL;
    var21 = 0;
    var16 = JS_FALSE;
    var17 = obj;
    var21 = argc;
    jsAvidemux();
    var16 = JS_TRUE;
    return var16;
}
static JSPropertySpec jjadm_static_ps[] = {
    {NULL, 0, 0, NULL, NULL}
};
static JSPropertySpec jjadm_ps[] = {
    {NULL, 0, 0, NULL, NULL}
};
static JSFunctionSpec jjadm_static_fs[] = {
    JS_FS("loadVideo", jjadmloadVideo, 1, 0, 3),
    JS_FS_END
};
static JSFunctionSpec jjadm_fs[] = {
    JS_FS_END
};
static JSClass jjadm_class = {
    "adm",
    0,
    JS_PropertyStub,
    JS_PropertyStub,
    JS_PropertyStub,
    JS_PropertyStub,
    JS_EnumerateStub,
    JS_ResolveStub,
    JS_ConvertStub,
    JS_FinalizeStub,
    NULL,
    NULL,
    NULL,
    jjadm__construct__,
    NULL,
    NULL,
    NULL,
    NULL
};
static JSObject *
jjadm_init(JSContext *cx, JSObject *obj)
{
    JSObject *parent_proto, *proto;
    JSClass *class;
    if (!cx || !obj) {
        JS_ReportError(cx, "invalid parameter");
        return NULL;
    }
    if (!JS_EnterLocalRootScope(cx)) {
        JS_ReportError(cx, "JS_EnterLocalRootScope failed");
        return NULL;
    }
    parent_proto = NULL;
    proto = NULL;
    parent_proto = JS_NewObject(cx, NULL, NULL, NULL);
    if (!parent_proto) {
        JS_LeaveLocalRootScope(cx);
        JS_ReportError(cx, "failed to create prototype");
        return NULL;
    }
    class = &jjadm_class;
    proto = JS_InitClass(cx, obj, parent_proto, class, jjadm__construct__, 0, jjadm_ps, jjadm_fs, jjadm_static_ps, jjadm_static_fs);
    if (!proto) {
        JS_LeaveLocalRootScope(cx);
        JS_ReportError(cx, "failed to init class");
        return NULL;
    }
    JS_LeaveLocalRootScope(cx);
    return proto;
}


JSObject *jsAvidemuxInit(JSContext *cx,JSObject *obj)
{
          if (JS_DefineFunctions(cx, obj, jj_static_fs) != JS_TRUE) 
          {
                return NULL;
          }
          return jjadm_init(cx,obj);
}

