%{
#include "stdio.h"
#include "ADM_jsAvidemux.h"
void jsAvidemux(void)
{
        printf("Constructor invoked\n");
}
%}
        /*            JSFUNC      C FUNC  PARAM     */
class adm
{
        function int loadVideo      : jsLoadVideo (cstring ) <static>;
        function int clearSegments  : jsClearSegments () <static>;
        function int appendVideo    : jsAppendVideo (cstring ) <static>;
        function int addSegment     : jsAddSegment (int ,double , double ) <static>;
        function int setPostProc    : jsSetPostProc (int ,int , int ) <static>;
        function int videoCodec_ignore     : jsVideoCodec(cstring,cstring[])   <static>;
        construct                   : jsAvidemux  ( ) <static>     ; 
};

%<

JSObject *jsAvidemuxInit(JSContext *cx,JSObject *obj)
{
          if (JS_DefineFunctions(cx, obj, jj_static_fs) != JS_TRUE) 
          {
                return NULL;
          }
          return jjadm_init(cx,obj);
}
%>
