// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList dgbob_param[]={
 {"thresh",offsetof(dgbob,thresh),"uint32_t",ADM_param_uint32_t},
 {"order",offsetof(dgbob,order),"bool",ADM_param_bool},
 {"mode",offsetof(dgbob,mode),"uint32_t",ADM_param_uint32_t},
 {"ap",offsetof(dgbob,ap),"bool",ADM_param_bool},
{NULL,0,NULL}
};
