// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "dgBob.h"
bool  dgbob_jserialize(const char *file, const dgbob *key){
admJson json;
json.addUint32("thresh",key->thresh);
json.addBool("order",key->order);
json.addUint32("mode",key->mode);
json.addBool("ap",key->ap);
return json.dumpToFile(file);
};
bool  dgbob_jdeserialize(const char *file, const ADM_paramList *tmpl,dgbob *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
