// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList deband_param[]={
 {"range",offsetof(deband,range),"uint32_t",ADM_param_uint32_t},
 {"lumaThreshold",offsetof(deband,lumaThreshold),"uint32_t",ADM_param_uint32_t},
 {"chromaThreshold",offsetof(deband,chromaThreshold),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
