// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList fade_param[]={
 {"startFade",offsetof(fade,startFade),"uint32_t",ADM_param_uint32_t},
 {"endFade",offsetof(fade,endFade),"uint32_t",ADM_param_uint32_t},
 {"inOut",offsetof(fade,inOut),"bool",ADM_param_bool},
 {"toBlack",offsetof(fade,toBlack),"bool",ADM_param_bool},
{NULL,0,NULL}
};
