// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "fade.h"
bool  fade_jserialize(const char *file, const fade *key){
admJson json;
json.addUint32("startFade",key->startFade);
json.addUint32("endFade",key->endFade);
json.addBool("inOut",key->inOut);
json.addBool("toBlack",key->toBlack);
return json.dumpToFile(file);
};
bool  fade_jdeserialize(const char *file, const ADM_paramList *tmpl,fade *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
