.TH "MP4" "3" "Version 0.9" "Cisco Systems Inc." "MP4 File Format Library"
.SH "NAME"
.LP 
\fBMP4AppendHintTrackSdp\fR \- Add to the SDP media level description of the hint track
.SH "SYNTAX"
.LP 
#include <mp4.h>
.LP 
bool \fBMP4AppendHintTrackSdp\fR(
.br 
	MP4FileHandle \fIhFile\fP,
.br 
	const char* sdpString
.br 
)
.SH "ARGUMENTS"
.LP 
.TP 
\fIhFile\fP
Specifies the mp4 file to which the operation applies.
.TP 
\fIsdpString\fP
Specifies the addition to the hint track sdp string.
.SH "RETURN VALUES"
.LP 
Upon success, true (1). Upon an error, false (0).
.SH "DESCRIPTION"
.LP 
\fBMP4AppendHintTrackSdp\fR appends the specified string to the SDP (IETF RFC 2327) media level fragment for the hint track. This is used by a streaming server to create a complete SDP description of the multimedia session represented by the file.

.SH "SEE ALSO"
.LP 
MP4(3) MP4GetHintTrackSdp(3) MP4SetHintTrackSdp(3)
