.TH "MP4" "3" "Version 0.9" "Cisco Systems Inc." "MP4 File Format Library"
.SH "NAME"
.LP 
\fBMP4GetTrackEditDwell\fR \- Get the dwell value of a track edit segment
.SH "SYNTAX"
.LP 
#include <mp4.h>
.LP 
MP4Duration \fBMP4GetTrackEditDwell\fR(
.br 
	MP4FileHandle \fIhFile\fP,
.br 
	MP4TrackId \fItrackId\fP,
.br 
	MP4EditId \fIeditId\fP
.br 
)
.SH "ARGUMENTS"
.LP 
.TP 
\fIhFile\fP
Specifies the mp4 file to which the operation applies.
.TP 
\fItrackId\fP
Specifies the track to which the operation applies.
.TP 
\fIeditId\fP
Specifies the edit segment for which the dwell value is desired.
.SH "RETURN VALUES"
.LP 
The dwell value of the edit segment of the track in the mp4 file.
.SH "DESCRIPTION"
.LP 
\fBMP4GetTrackEditDwell\fR returns the dwell value of the specified track edit segment. A value of true (1) indicates that during this edit segment the media will be paused; a value of false (0) indicates that during this edit segment the media will be played at its normal rate.
.SH "SEE ALSO"
.LP 
MP4(3) MP4SetTrackEditDwell(3)
