.TH "MP4" "3" "Version 0.9" "Cisco Systems Inc." "MP4 File Format Library"
.SH "NAME"
.LP 
\fBMP4GetRtpTimestampStart\fR \- Get the RTP start time of a hint track
.SH "SYNTAX"
.LP 
#include <mp4.h>
.LP 
MP4Timestamp \fBMP4GetRtpTimestampStart\fR(
.br 
	MP4FileHandle \fIhFile\fP,
.br 
	MP4TrackId \fIhintTrackId\fP
.br 
);
.SH "ARGUMENTS"
.LP 
.TP 
\fIhFile\fP
Specifies the mp4 file to which the operation applies.
.TP 
\fItrackId\fP
Specifies the hint track to which the operation applies.


.SH "RETURN VALUES"
.LP 
Upon success, the RTP start time in the RTP time scale which is identical to the hint track time scale. Upon an error, MP4_INVALID_TIMESTAMP.
.SH "DESCRIPTION"
.LP 
\fBMP4GetRtpTimestampStart\fR returns the RTP timestamp start of the specified hint track. Typically this is a random value that is chosen when the first RTP packet is constructed by the MP4 library. However the  value can be set explicitly for the hint track and stored. Typically this is used if it is desired that timestamps start at zero.
.LP 
An application will need this value in order to construct RTCP Sender Reports that relate the hint track time to an real time clock. The mp4broadcaster test program provided with the MP4 library gives an example of this.
.LP 
See IETF RFC 1889 for details regarding RTP timestamps and RTCP.
.SH "SEE ALSO"
.LP 
MP4(3) MP4SetRtpTimestampStart(3)
