.TH "MP4" "3" "Version 0.9" "Cisco Systems Inc." "MP4 File Format Library"
.SH "NAME"
.LP 
\fBMP4SetTrackEditMediaStart\fR \- Set the media start time of a track edit segment
.SH "SYNTAX"
.LP 
#include <mp4.h>
.LP 
bool \fBMP4SetTrackEditMediaStart\fR(
.br 
	MP4FileHandle \fIhFile\fP,
.br 
	MP4TrackId \fItrackId\fP,
.br 
	MP4EditId \fIeditId\fP,
.br 
	MP4Timestamp \fImediaStartTime\fP
.br 
);
.SH "ARGUMENTS"
.LP 
.TP 
\fIhFile\fP
Specifies the mp4 file to which the operation applies.
.TP 
\fItrackId\fP
Specifies the track to which the operation applies.
.TP 
\fIeditId\fP
Specifies the edit segment to which the operation applies. Caveat: the first edit has id 1 not 0.
.TP 
\fImediaStartTime\fP
Species the new value for the media start in track time scale units.

.SH "RETURN VALUES"
.LP 
Upon success, true (1). Upon an error, false (0).

.SH "DESCRIPTION"
.LP 
\fBMP4SetTrackEditMediaStart\fR sets the media start time of the specified edit segment from the specified track in the track time scale units. See MP4ConvertToTrackTimestamp() for how to map this value from another time scale.
.LP 
Note that this differs from the edit segment start time. For example:
.LP 
EditId	Start	MediaStart	Duration
1		0		15			30
.br 
2		30		120			20
.br 	
3		50		3000			10

.SH "SEE ALSO"
.LP 
MP4(3) MP4GetTrackEditMediaStart(3)
