// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList blur_param[]={
 {"left",offsetof(blur,left),"uint32_t",ADM_param_uint32_t},
 {"right",offsetof(blur,right),"uint32_t",ADM_param_uint32_t},
 {"top",offsetof(blur,top),"uint32_t",ADM_param_uint32_t},
 {"bottom",offsetof(blur,bottom),"uint32_t",ADM_param_uint32_t},
 {"algorithm",offsetof(blur,algorithm),"uint32_t",ADM_param_uint32_t},
 {"radius",offsetof(blur,radius),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
