// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
bool c1en;
float c1u;
float c1v;
float c1dist;
float c1slope;
bool c2en;
float c2u;
float c2v;
float c2dist;
float c2slope;
bool c3en;
float c3u;
float c3v;
float c3dist;
float c3slope;
}artChromaHold;
