// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList artChromaHold_param[]={
 {"c1en",offsetof(artChromaHold,c1en),"bool",ADM_param_bool},
 {"c1u",offsetof(artChromaHold,c1u),"float",ADM_param_float},
 {"c1v",offsetof(artChromaHold,c1v),"float",ADM_param_float},
 {"c1dist",offsetof(artChromaHold,c1dist),"float",ADM_param_float},
 {"c1slope",offsetof(artChromaHold,c1slope),"float",ADM_param_float},
 {"c2en",offsetof(artChromaHold,c2en),"bool",ADM_param_bool},
 {"c2u",offsetof(artChromaHold,c2u),"float",ADM_param_float},
 {"c2v",offsetof(artChromaHold,c2v),"float",ADM_param_float},
 {"c2dist",offsetof(artChromaHold,c2dist),"float",ADM_param_float},
 {"c2slope",offsetof(artChromaHold,c2slope),"float",ADM_param_float},
 {"c3en",offsetof(artChromaHold,c3en),"bool",ADM_param_bool},
 {"c3u",offsetof(artChromaHold,c3u),"float",ADM_param_float},
 {"c3v",offsetof(artChromaHold,c3v),"float",ADM_param_float},
 {"c3dist",offsetof(artChromaHold,c3dist),"float",ADM_param_float},
 {"c3slope",offsetof(artChromaHold,c3slope),"float",ADM_param_float},
{NULL,0,NULL}
};
