// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList vaapiFilter_param[]={
 {"targetWidth",offsetof(vaapiFilter,targetWidth),"uint32_t",ADM_param_uint32_t},
 {"targetHeight",offsetof(vaapiFilter,targetHeight),"uint32_t",ADM_param_uint32_t},
 {"mpeg2ToPC",offsetof(vaapiFilter,mpeg2ToPC),"bool",ADM_param_bool},
{NULL,0,NULL}
};
