// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList vaapiFilterDeint_param[]={
 {"deintMode",offsetof(vaapiFilterDeint,deintMode),"uint32_t",ADM_param_uint32_t},
 {"fieldOrder",offsetof(vaapiFilterDeint,fieldOrder),"uint32_t",ADM_param_uint32_t},
 {"framePerField",offsetof(vaapiFilterDeint,framePerField),"uint32_t",ADM_param_uint32_t},
 {"targetWidth",offsetof(vaapiFilterDeint,targetWidth),"uint32_t",ADM_param_uint32_t},
 {"targetHeight",offsetof(vaapiFilterDeint,targetHeight),"uint32_t",ADM_param_uint32_t},
 {"resize",offsetof(vaapiFilterDeint,resize),"bool",ADM_param_bool},
{NULL,0,NULL}
};
