// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "vaapiFilter.h"
bool  vaapiFilter_jserialize(const char *file, const vaapiFilter *key){
admJson json;
json.addUint32("targetWidth",key->targetWidth);
json.addUint32("targetHeight",key->targetHeight);
json.addBool("mpeg2ToPC",key->mpeg2ToPC);
return json.dumpToFile(file);
};
bool  vaapiFilter_jdeserialize(const char *file, const ADM_paramList *tmpl,vaapiFilter *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
