// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList ffnvenc_encoder_param[]={
 {"rc_mode",offsetof(ffnvenc_encoder,rc_mode),"uint32_t",ADM_param_uint32_t},
 {"preset",offsetof(ffnvenc_encoder,preset),"uint32_t",ADM_param_uint32_t},
 {"quality",offsetof(ffnvenc_encoder,quality),"uint32_t",ADM_param_uint32_t},
 {"gopsize",offsetof(ffnvenc_encoder,gopsize),"uint32_t",ADM_param_uint32_t},
 {"bframes",offsetof(ffnvenc_encoder,bframes),"uint32_t",ADM_param_uint32_t},
 {"bitrate",offsetof(ffnvenc_encoder,bitrate),"uint32_t",ADM_param_uint32_t},
 {"max_bitrate",offsetof(ffnvenc_encoder,max_bitrate),"uint32_t",ADM_param_uint32_t},
 {"twopass",offsetof(ffnvenc_encoder,twopass),"bool",ADM_param_bool},
{NULL,0,NULL}
};
