// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList fadeInOut_param[]={
 {"startTime",offsetof(fadeInOut,startTime),"uint32_t",ADM_param_uint32_t},
 {"endTime",offsetof(fadeInOut,endTime),"uint32_t",ADM_param_uint32_t},
 {"rgbColor",offsetof(fadeInOut,rgbColor),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
