// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
uint32_t method;
uint32_t algo;
uint32_t pad;
float yaw;
float pitch;
float roll;
float fov;
float distortion;
}flat360;
