// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList flat360_param[]={
 {"method",offsetof(flat360,method),"uint32_t",ADM_param_uint32_t},
 {"algo",offsetof(flat360,algo),"uint32_t",ADM_param_uint32_t},
 {"pad",offsetof(flat360,pad),"uint32_t",ADM_param_uint32_t},
 {"yaw",offsetof(flat360,yaw),"float",ADM_param_float},
 {"pitch",offsetof(flat360,pitch),"float",ADM_param_float},
 {"roll",offsetof(flat360,roll),"float",ADM_param_float},
 {"fov",offsetof(flat360,fov),"float",ADM_param_float},
 {"distortion",offsetof(flat360,distortion),"float",ADM_param_float},
{NULL,0,NULL}
};
