// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList artGrid_param[]={
 {"size",offsetof(artGrid,size),"uint32_t",ADM_param_uint32_t},
 {"roll",offsetof(artGrid,roll),"bool",ADM_param_bool},
{NULL,0,NULL}
};
