// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList nvencconf_param[]={
 {"preset",offsetof(nvencconf,preset),"uint32_t",ADM_param_uint32_t},
 {"bitrate",offsetof(nvencconf,bitrate),"uint32_t",ADM_param_uint32_t},
 {"max_bitrate",offsetof(nvencconf,max_bitrate),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
