// automatically generated by admSerialization.py do not edit
#ifndef ADM_nvencconf_CONF_H
#define ADM_nvencconf_CONF_H
typedef struct {
uint32_t preset;
uint32_t bitrate;
uint32_t max_bitrate;
}nvencconf;
#endif
