// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "rotate.h"
bool  gl_rotate_jserialize(const char *file, const gl_rotate *key){
admJson json;
json.addInt32("angle",key->angle);
return json.dumpToFile(file);
};
bool  gl_rotate_jdeserialize(const char *file, const ADM_paramList *tmpl,gl_rotate *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
