HEADERS = \
../avidemux/ADM_assert.h \ 
../avidemux/ADM_audio/ADM_a52info.h \ 
../avidemux/ADM_audio/ADM_aacinfo.h \ 
../avidemux/ADM_audio/ADM_audiodef.h \ 
../avidemux/ADM_audio/ADM_dcainfo.h \ 
../avidemux/ADM_audio/ADM_mp3info.h \ 
../avidemux/ADM_audio/audioex.h \ 
../avidemux/ADM_audio/audiosource_ext.h \ 
../avidemux/ADM_audiocodec/ADM_audiocodec.h \ 
../avidemux/ADM_audiocodec/ADM_audiocodeclist.h \ 
../avidemux/ADM_audiocodec/adm_ogg.h \ 
../avidemux/ADM_audiocodec/ADM_vorbis.h \ 
../avidemux/ADM_audiodevice/ADM_audiodevice.h \ 
../avidemux/ADM_audiodevice/ADM_deviceALSA.h \ 
../avidemux/ADM_audiodevice/ADM_deviceArts.h \ 
../avidemux/ADM_audiodevice/ADM_deviceAudioCore.h \ 
../avidemux/ADM_audiodevice/ADM_deviceEsd.h \ 
../avidemux/ADM_audiodevice/ADM_deviceJack.h \ 
../avidemux/ADM_audiodevice/ADM_deviceoss.h \ 
../avidemux/ADM_audiodevice/ADM_deviceSDL.h \ 
../avidemux/ADM_audiodevice/ADM_deviceWin32.h \ 
../avidemux/ADM_audiodevice/audio_out.h \ 
../avidemux/ADM_audiofilter/audioencoder.h \ 
../avidemux/ADM_audiofilter/audioencoder_aften.h \ 
../avidemux/ADM_audiofilter/audioencoder_aften_param.h \ 
../avidemux/ADM_audiofilter/audioencoder_config.h \ 
../avidemux/ADM_audiofilter/audioencoder_faac.h \ 
../avidemux/ADM_audiofilter/audioencoder_faac_param.h \ 
../avidemux/ADM_audiofilter/audioencoder_lame.h \ 
../avidemux/ADM_audiofilter/audioencoder_lame_param.h \ 
../avidemux/ADM_audiofilter/audioencoder_lavcodec.h \ 
../avidemux/ADM_audiofilter/audioencoder_pcm.h \ 
../avidemux/ADM_audiofilter/audioencoder_twolame.h \ 
../avidemux/ADM_audiofilter/audioencoder_twolame_param.h \ 
../avidemux/ADM_audiofilter/audioencoder_vorbis.h \ 
../avidemux/ADM_audiofilter/audioencoder_vorbis_param.h \ 
../avidemux/ADM_audiofilter/audioeng_buildfilters.h \ 
../avidemux/ADM_audiofilter/audioeng_process.h \ 
../avidemux/ADM_audiofilter/audiofilter_bridge.h \ 
../avidemux/ADM_audiofilter/audiofilter_channel_route.h \ 
../avidemux/ADM_audiofilter/audiofilter_dolby.h \ 
../avidemux/ADM_audiofilter/audiofilter_film2pal.h \ 
../avidemux/ADM_audiofilter/audiofilter_limiter.h \ 
../avidemux/ADM_audiofilter/audiofilter_limiter_param.h \ 
../avidemux/ADM_audiofilter/audiofilter_mixer.h \ 
../avidemux/ADM_audiofilter/audiofilter_normalize.h \ 
../avidemux/ADM_audiofilter/audiofilter_normalize_param.h \ 
../avidemux/ADM_audiofilter/audiofilter_sox.h \ 
../avidemux/ADM_audiofilter/audiolib_sox.h \ 
../avidemux/ADM_audiofilter/audio_raw.h \ 
../avidemux/ADM_audiofilter/resampl.h \ 
../avidemux/ADM_codecs/ADM_codec.h \ 
../avidemux/ADM_codecs/ADM_codecNull.h \ 
../avidemux/ADM_codecs/ADM_ffmp43.h \ 
../avidemux/ADM_codecs/ADM_ffmpeg.h \ 
../avidemux/ADM_codecs/ADM_ffmpegConfig.h \ 
../avidemux/ADM_codecs/ADM_mjpeg.h \ 
../avidemux/ADM_codecs/ADM_mjpegEncode.h \ 
../avidemux/ADM_codecs/ADM_mpeg.h \ 
../avidemux/ADM_codecs/ADM_png.h \ 
../avidemux/ADM_codecs/ADM_rgb16.h \ 
../avidemux/ADM_codecs/ADM_theora_dec.h \ 
../avidemux/ADM_codecs/ADM_theora_enc.h \ 
../avidemux/ADM_codecs/ADM_uyvy.h \ 
../avidemux/ADM_codecs/ADM_x264.h \ 
../avidemux/ADM_codecs/ADM_x264param.h \ 
../avidemux/ADM_codecs/ADM_xvid.h \ 
../avidemux/ADM_codecs/ADM_xvid4.h \ 
../avidemux/ADM_codecs/ADM_xvid4param.h \ 
../avidemux/ADM_codecs/ADM_xvideco.h \ 
../avidemux/ADM_colorspace/ADM_colorspace.h \ 
../avidemux/ADM_colorspace/ADM_rgb.h \ 
../avidemux/ADM_colorspace/colorspace.h \ 
../avidemux/ADM_editor/ADM_edCache.h \ 
../avidemux/ADM_editor/ADM_outputfmt.h \ 
../avidemux/ADM_editor/ADM_Video.h \ 
../avidemux/ADM_encoder/ADM_encCodecDesc.h \ 
../avidemux/ADM_encoder/adm_encConfig.h \ 
../avidemux/ADM_encoder/adm_encCopy.h \ 
../avidemux/ADM_encoder/adm_encdivx.h \ 
../avidemux/ADM_encoder/adm_encffmatrix.h \ 
../avidemux/ADM_encoder/adm_encffmpeg.h \ 
../avidemux/ADM_encoder/adm_encmjpeg.h \ 
../avidemux/ADM_encoder/adm_encmjpeg_param.h \ 
../avidemux/ADM_encoder/adm_encmpeg2enc.h \ 
../avidemux/ADM_encoder/adm_encoder.h \ 
../avidemux/ADM_encoder/adm_encRequant.h \ 
../avidemux/ADM_encoder/adm_encx264.h \ 
../avidemux/ADM_encoder/adm_encxvid.h \ 
../avidemux/ADM_encoder/adm_encXvid4.h \ 
../avidemux/ADM_encoder/adm_encyv12.h \ 
../avidemux/ADM_encoder/ADM_videocodeclist.h \ 
../avidemux/ADM_encoder/xvid_vbr.h \ 
../avidemux/ADM_filter/video_filters.h \ 
../avidemux/ADM_filter/vidVCD.h \ 
../avidemux/ADM_infoExtractor/ADM_h264_tag.h \ 
../avidemux/ADM_inputs/ADM_amv/ADM_amv.h \ 
../avidemux/ADM_inputs/ADM_asf/ADM_asf.h \ 
../avidemux/ADM_inputs/ADM_asf/ADM_asfIo.h \ 
../avidemux/ADM_inputs/ADM_asf/ADM_asfPacket.h \ 
../avidemux/ADM_inputs/ADM_avsproxy/ADM_avsproxy.h \ 
../avidemux/ADM_inputs/ADM_avsproxy/ADM_avsproxy_internal.h \ 
../avidemux/ADM_inputs/ADM_flv/ADM_flv.h \ 
../avidemux/ADM_inputs/ADM_h263/ADM_h263.h \ 
../avidemux/ADM_inputs/ADM_h263/bitsRead.h \ 
../avidemux/ADM_inputs/ADM_inpics/ADM_pics.h \ 
../avidemux/ADM_inputs/ADM_inpics/bitmap.h \ 
../avidemux/ADM_inputs/ADM_matroska/ADM_ebml.h \ 
../avidemux/ADM_inputs/ADM_matroska/ADM_mkv.h \ 
../avidemux/ADM_inputs/ADM_matroska/mkv_tagenum.h \ 
../avidemux/ADM_inputs/ADM_matroska/mkv_tags.h \ 
../avidemux/ADM_inputs/ADM_mp4/ADM_atom.h \ 
../avidemux/ADM_inputs/ADM_mp4/ADM_mp4.h \ 
../avidemux/ADM_inputs/ADM_mp4/ADM_mp4Leaf.h \ 
../avidemux/ADM_inputs/ADM_mp4/ADM_mp4Tree.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_audio.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_demuxer.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_demuxerEs.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_demuxerMSDVR.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_demuxerPS.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_demuxerTS.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_identify.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_indexer.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_indexer_internal.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_io.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_mpegstartcode.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_probe.h \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_video.h \ 
../avidemux/ADM_inputs/ADM_nuv/ADM_nuv.h \ 
../avidemux/ADM_inputs/ADM_nuv/ADM_rtGlob.h \ 
../avidemux/ADM_inputs/ADM_nuv/lzoconf.h \ 
../avidemux/ADM_inputs/ADM_nuv/minilzo.h \ 
../avidemux/ADM_inputs/ADM_nuv/mmx.h \ 
../avidemux/ADM_inputs/ADM_nuv/nuppel.h \ 
../avidemux/ADM_inputs/ADM_nuv/RTjpeg.h \ 
../avidemux/ADM_inputs/ADM_nuv/RTjpegN.h \ 
../avidemux/ADM_inputs/ADM_ogm/ADM_oghead.h \ 
../avidemux/ADM_inputs/ADM_ogm/ADM_ogm.h \ 
../avidemux/ADM_inputs/ADM_ogm/ADM_ogmpages.h \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_odml_audio.h \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_openDML.h \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_riff.h \ 
../avidemux/ADM_lavcodec.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ac3.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ac3tab.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/allcodecs.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/avcodec.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/bitstream.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/bytestream.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/cabac.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/dnxhddata.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/dsputil.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/dsputil_cpu.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/dvdata.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/eval.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/faandct.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/fastmemcpy.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ffconf.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/golomb.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/h261.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/h261data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/h263.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/h263data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/h263_parser.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/h264.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/h264data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/h264_parser.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/i386/dsputil_mmx_avg.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/i386/dsputil_mmx_qns.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/i386/dsputil_mmx_rnd.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/i386/mathops.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/i386/mmx.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/i386/vp3dsp_mmx.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/i386/vp3dsp_sse2.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/imgconvert_template.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/indeo2data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/indeo3data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/jpeglsdec.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mathops.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mjpeg.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mjpegdec.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mjpegenc.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpeg12.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpeg12data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpeg12decdata.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpeg4data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpeg4video_parser.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpegaudio.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpegaudiodata.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpegaudiodecheader.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpegaudiodectab.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpegaudiotab.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpegvideo.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/mpegvideo_common.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/msmpeg4.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/msmpeg4data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/msmpeg4tab.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/oggvorbis.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/opt.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/os_support.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/parser.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ppc/dsputil_altivec.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ppc/dsputil_ppc.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ppc/gcc_fixes.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ppc/mathops.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ppc/types_altivec.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/qdm2data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ra144.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ra288.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/rangecoder.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/ratecontrol.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/raw.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/rl.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/roqvideo.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/simple_idct.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/snow.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/sp5x.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/svq1.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/svq1_cb.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/svq1_vlc.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/truemotion1data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/vc1.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/vc1acdata.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/vc1data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/vp3data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/vp56.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/vp56data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/vp5data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/vp6data.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/wma.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/wmadata.h \ 
../avidemux/ADM_libraries/ADM_lavcodec/xiph.h \ 
../avidemux/ADM_libraries/ADM_lavformat/ADM_lavformat.h \ 
../avidemux/ADM_libraries/ADM_lavformat/ADM_tscrc.h \ 
../avidemux/ADM_libraries/ADM_lavformat/allformats.h \ 
../avidemux/ADM_libraries/ADM_lavformat/avformat.h \ 
../avidemux/ADM_libraries/ADM_lavformat/avi.h \ 
../avidemux/ADM_libraries/ADM_lavformat/avio.h \ 
../avidemux/ADM_libraries/ADM_lavformat/dv.h \ 
../avidemux/ADM_libraries/ADM_lavformat/flv.h \ 
../avidemux/ADM_libraries/ADM_lavformat/isom.h \ 
../avidemux/ADM_libraries/ADM_lavformat/matroska.h \ 
../avidemux/ADM_libraries/ADM_lavformat/mov.h \ 
../avidemux/ADM_libraries/ADM_lavformat/mpeg.h \ 
../avidemux/ADM_libraries/ADM_lavformat/mpegts.h \ 
../avidemux/ADM_libraries/ADM_lavformat/qtpalette.h \ 
../avidemux/ADM_libraries/ADM_lavformat/riff.h \ 
../avidemux/ADM_libraries/ADM_lavformat/rtp.h \ 
../avidemux/ADM_libraries/ADM_lavformat/rtsp.h \ 
../avidemux/ADM_libraries/ADM_lavformat/rtspcodes.h \ 
../avidemux/ADM_libraries/ADM_lavutil/adler32.h \ 
../avidemux/ADM_libraries/ADM_lavutil/avstring.h \ 
../avidemux/ADM_libraries/ADM_lavutil/avutil.h \ 
../avidemux/ADM_libraries/ADM_lavutil/bswap.h \ 
../avidemux/ADM_libraries/ADM_lavutil/common.h \ 
../avidemux/ADM_libraries/ADM_lavutil/crc.h \ 
../avidemux/ADM_libraries/ADM_lavutil/fifo.h \ 
../avidemux/ADM_libraries/ADM_lavutil/integer.h \ 
../avidemux/ADM_libraries/ADM_lavutil/internal.h \ 
../avidemux/ADM_libraries/ADM_lavutil/intfloat_readwrite.h \ 
../avidemux/ADM_libraries/ADM_lavutil/intreadwrite.h \ 
../avidemux/ADM_libraries/ADM_lavutil/lls.h \ 
../avidemux/ADM_libraries/ADM_lavutil/log.h \ 
../avidemux/ADM_libraries/ADM_lavutil/mathematics.h \ 
../avidemux/ADM_libraries/ADM_lavutil/md5.h \ 
../avidemux/ADM_libraries/ADM_lavutil/mem.h \ 
../avidemux/ADM_libraries/ADM_lavutil/random.h \ 
../avidemux/ADM_libraries/ADM_lavutil/rational.h \ 
../avidemux/ADM_libraries/ADM_lavutil/x86_cpu.h \ 
../avidemux/ADM_libraries/ADM_liba52/a52.h \ 
../avidemux/ADM_libraries/ADM_liba52/a52_internal.h \ 
../avidemux/ADM_libraries/ADM_liba52/attributes.h \ 
../avidemux/ADM_libraries/ADM_liba52/bitstream.h \ 
../avidemux/ADM_libraries/ADM_liba52/mm_accel.h \ 
../avidemux/ADM_libraries/ADM_liba52/tables.h \ 
../avidemux/ADM_libraries/ADM_libass/ass.h \ 
../avidemux/ADM_libraries/ADM_libass/ass_bitmap.h \ 
../avidemux/ADM_libraries/ADM_libass/ass_cache.h \ 
../avidemux/ADM_libraries/ADM_libass/ass_font.h \ 
../avidemux/ADM_libraries/ADM_libass/ass_fontconfig.h \ 
../avidemux/ADM_libraries/ADM_libass/ass_library.h \ 
../avidemux/ADM_libraries/ADM_libass/ass_types.h \ 
../avidemux/ADM_libraries/ADM_libass/ass_utils.h \ 
../avidemux/ADM_libraries/ADM_libass/help_mp.h \ 
../avidemux/ADM_libraries/ADM_libass/mputils.h \ 
../avidemux/ADM_libraries/ADM_libMad/bit.h \ 
../avidemux/ADM_libraries/ADM_libMad/decoder.h \ 
../avidemux/ADM_libraries/ADM_libMad/fixed.h \ 
../avidemux/ADM_libraries/ADM_libMad/frame.h \ 
../avidemux/ADM_libraries/ADM_libMad/global.h \ 
../avidemux/ADM_libraries/ADM_libMad/huffman.h \ 
../avidemux/ADM_libraries/ADM_libMad/layer12.h \ 
../avidemux/ADM_libraries/ADM_libMad/layer3.h \ 
../avidemux/ADM_libraries/ADM_libMad/mad.h \ 
../avidemux/ADM_libraries/ADM_libMad/madmem.h \ 
../avidemux/ADM_libraries/ADM_libMad/stream.h \ 
../avidemux/ADM_libraries/ADM_libMad/synth.h \ 
../avidemux/ADM_libraries/ADM_libMad/timer.h \ 
../avidemux/ADM_libraries/ADM_libMad/version.h \ 
../avidemux/ADM_libraries/ADM_libMpeg2Dec/attributes.h \ 
../avidemux/ADM_libraries/ADM_libMpeg2Dec/convert.h \ 
../avidemux/ADM_libraries/ADM_libMpeg2Dec/mmx.h \ 
../avidemux/ADM_libraries/ADM_libMpeg2Dec/mpeg2.h \ 
../avidemux/ADM_libraries/ADM_libMpeg2Dec/mpeg2_cpu.h \ 
../avidemux/ADM_libraries/ADM_libMpeg2Dec/mpeg2_internal.h \ 
../avidemux/ADM_libraries/ADM_libMpeg2Dec/video_out.h \ 
../avidemux/ADM_libraries/ADM_libMpeg2Dec/vlc.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/ADM_mpeg2enc.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/ADM_mpeg2Param.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/altivec_conf.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/altivec_motion.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/altivec_predict.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/altivec_quantize.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/altivec_transform.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/amber.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/benchmark.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/mjpeg_logging.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/mjpeg_types.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/quantize_precomp.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/quantize_ref.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/syntaxconsts.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/vectorize.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/altivec/verify.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/attributes.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/cpu_accel.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/fastintfns.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/format_codes.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/global.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/mblock_sub44_sads_x86.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/mjpeg_logging.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/mjpeg_types.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/mmx.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/mmxsse_motion.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/motionsearch.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/mpeg2enc.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/mpeg2parm.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/mpegconsts.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/predict_ref.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/quantize_ref.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/simd.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/synchrolib.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/syntaxparams.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/tables.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/transfrm_ref.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/vlc.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/yuv4mpeg.h \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/yuv4mpeg_intern.h \ 
../avidemux/ADM_libraries/ADM_libpostproc/mangle.h \ 
../avidemux/ADM_libraries/ADM_libpostproc/postprocess.h \ 
../avidemux/ADM_libraries/ADM_libpostproc/postprocess_internal.h \ 
../avidemux/ADM_libraries/ADM_libsdl/SDLMain.h \ 
../avidemux/ADM_libraries/ADM_libswscale/ADM_mp.h \ 
../avidemux/ADM_libraries/ADM_libswscale/rgb2rgb.h \ 
../avidemux/ADM_libraries/ADM_libswscale/swscale.h \ 
../avidemux/ADM_libraries/ADM_libswscale/swscale_internal.h \ 
../avidemux/ADM_libraries/ADM_libswscale/wrapper.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/absthr.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/ath.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/availbits.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/bitbuffer.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/common.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/crc.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/critband.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/dab.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/encode.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/encoder.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/encode_new.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/energy.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/enwindow.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/fft.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/freqtable.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/mem.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/musicin.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/psycho_0.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/psycho_1.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/psycho_1_critband.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/psycho_1_freqtable.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/psycho_2.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/psycho_2_absthr.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/psycho_3.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/psycho_4.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/psycho_n1.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/subband.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/tables.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/twolame.h \ 
../avidemux/ADM_libraries/ADM_libtwolame/util.h \ 
../avidemux/ADM_libraries/ADM_libwrapper/libwrapper.h \ 
../avidemux/ADM_libraries/ADM_libwrapper/libwrapper_amrnb.h \ 
../avidemux/ADM_libraries/ADM_libwrapper/libwrapper_dca.h \ 
../avidemux/ADM_libraries/ADM_libwrapper/libwrapper_global.h \ 
../avidemux/ADM_libraries/ADM_lvemux/ADM_muxer.h \ 
../avidemux/ADM_libraries/ADM_lvemux/mux_out.h \ 
../avidemux/ADM_libraries/ADM_mplex/ADM_inout.h \ 
../avidemux/ADM_libraries/ADM_mplex/ADM_mthread.h \ 
../avidemux/ADM_libraries/ADM_mplex/ADM_transfert.h \ 
../avidemux/ADM_libraries/ADM_mplex/cpu_accel.h \ 
../avidemux/ADM_libraries/ADM_mplex/format_codes.h \ 
../avidemux/ADM_libraries/ADM_mplex/mjpeg_logging.h \ 
../avidemux/ADM_libraries/ADM_mplex/mjpeg_types.h \ 
../avidemux/ADM_libraries/ADM_mplex/mpegconsts.h \ 
../avidemux/ADM_libraries/ADM_mplex/streamType.h \ 
../avidemux/ADM_libraries/ADM_mplex/yuv4mpeg.h \ 
../avidemux/ADM_libraries/ADM_mplex/yuv4mpeg_intern.h \ 
../avidemux/ADM_libraries/ADM_nvwa/debug_new.h \ 
../avidemux/ADM_libraries/ADM_nvwa/fast_mutex.h \ 
../avidemux/ADM_libraries/ADM_nvwa/static_assert.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsapi.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsarena.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsarray.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsatom.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsautocfg.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsbit.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsbool.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsclist.h \ 
../avidemux/ADM_libraries/ADM_smjs/jscntxt.h \ 
../avidemux/ADM_libraries/ADM_smjs/jscompat.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsconfig.h \ 
../avidemux/ADM_libraries/ADM_smjs/jscpucfg.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsdate.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsdbgapi.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsdhash.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsdtoa.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsemit.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsexn.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsfile.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsfun.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsgc.h \ 
../avidemux/ADM_libraries/ADM_smjs/jshash.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsinterp.h \ 
../avidemux/ADM_libraries/ADM_smjs/jslibmath.h \ 
../avidemux/ADM_libraries/ADM_smjs/jslock.h \ 
../avidemux/ADM_libraries/ADM_smjs/jslong.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsmath.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsnum.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsobj.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsopcode.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsosdep.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsotypes.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsparse.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsprf.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsprvtd.h \ 
../avidemux/ADM_libraries/ADM_smjs/jspubtd.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsregexp.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsscan.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsscope.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsscript.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsstddef.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsstr.h \ 
../avidemux/ADM_libraries/ADM_smjs/jstypes.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsutil.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsxdrapi.h \ 
../avidemux/ADM_libraries/ADM_smjs/jsxml.h \ 
../avidemux/ADM_libraries/ADM_smjs/prmjtime.h \ 
../avidemux/ADM_libraries/ADM_smjs/resource.h \ 
../avidemux/ADM_libraries/ADM_utilities/admmangle.h \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_bitstream.h \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_compressedImage.h \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_fileio.h \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_image.h \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_pp.h \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_print_priv.h \ 
../avidemux/ADM_libraries/ADM_utilities/avidemutils.h \ 
../avidemux/ADM_libraries/ADM_utilities/avifmt.h \ 
../avidemux/ADM_libraries/ADM_utilities/avifmt2.h \ 
../avidemux/ADM_libraries/ADM_utilities/default.h \ 
../avidemux/ADM_libraries/ADM_utilities/fourcc.h \ 
../avidemux/ADM_libraries/ADM_utilities/subchunk.h \ 
../avidemux/ADM_libraries/ADM_xvidratectl/ADM_ratecontrol.h \ 
../avidemux/ADM_libraries/ADM_xvidratectl/ADM_xvidr_internal.h \ 
../avidemux/ADM_ocr/adm_glyph.h \ 
../avidemux/ADM_ocr/ADM_leftturn.h \ 
../avidemux/ADM_ocr/ADM_ocr.h \ 
../avidemux/ADM_ocr/ADM_ocrInternal.h \ 
../avidemux/ADM_osSupport/ADM_cpuCap.h \ 
../avidemux/ADM_osSupport/ADM_debug.h \ 
../avidemux/ADM_osSupport/ADM_debugID.h \ 
../avidemux/ADM_osSupport/ADM_misc.h \ 
../avidemux/ADM_osSupport/ADM_queue.h \ 
../avidemux/ADM_osSupport/ADM_quota.h \ 
../avidemux/ADM_osSupport/ADM_threads.h \ 
../avidemux/ADM_osSupport/TLK_clock.h \ 
../avidemux/ADM_outputs/oplug_avi/avilist.h \ 
../avidemux/ADM_outputs/oplug_avi/GUI_mux.h \ 
../avidemux/ADM_outputs/oplug_avi/op_avisave.h \ 
../avidemux/ADM_outputs/oplug_avi/op_savecopy.h \ 
../avidemux/ADM_outputs/oplug_avi/op_saveprocess.h \ 
../avidemux/ADM_outputs/oplug_flv/oplug_flv.h \ 
../avidemux/ADM_outputs/oplug_mp4/oplug_mp4.h \ 
../avidemux/ADM_outputs/oplug_mpegFF/oplug_encodervcd.h \ 
../avidemux/ADM_outputs/oplug_mpegFF/oplug_vcdff.h \ 
../avidemux/ADM_outputs/oplug_ogm/op_ogpage.h \ 
../avidemux/ADM_outputs/oplug_ogm/op_ogsave.h \ 
../avidemux/ADM_requant/getvlc.h \ 
../avidemux/ADM_requant/putvlc.h \ 
../avidemux/ADM_requant/tcrequant.h \ 
../avidemux/ADM_script/ADM_Avidemux.h \ 
../avidemux/ADM_script/ADM_AvidemuxAudio.h \ 
../avidemux/ADM_script/ADM_AvidemuxVideo.h \ 
../avidemux/ADM_script/ADM_container.h \ 
../avidemux/ADM_script/ADM_JSAvidemux.h \ 
../avidemux/ADM_script/ADM_JSAvidemuxAudio.h \ 
../avidemux/ADM_script/ADM_JSAvidemuxVideo.h \ 
../avidemux/ADM_script/ADM_JSDirectorySearch.h \ 
../avidemux/ADM_script/ADM_JSGlobal.h \ 
../avidemux/ADM_script/adm_scanner.h \ 
../avidemux/ADM_script/DirectorySearch.h \ 
../avidemux/ADM_script/StdFile.h \ 
../avidemux/ADM_toolkit/ADM_audioQueue.h \ 
../avidemux/ADM_toolkit/ADM_intfloat.h \ 
../avidemux/ADM_toolkit/ADM_packetQueue.h \ 
../avidemux/ADM_toolkit/bitmap.h \ 
../avidemux/ADM_toolkit/filesel.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/ADM_tray.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_busy.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_encoding.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_enter.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_factory.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyAsharp.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyChromaShift.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyContrast.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyCrop.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyDialog.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyEq2.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyEraser.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyHue.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyParticle.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyPreview.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flySrtPos.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flySwissArmyKnife.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyThreshold.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_idx_pg.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_resizeWiz.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_working.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/GUI_accelRender.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/GUI_render.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/GUI_sdlRender.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/GUI_ui.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/GUI_xvRender.h \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/systray.h \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/ADM_flyTemplate.h \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/DIA_flyDialogQt4.h \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_gui/ADM_qslider.h \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_gui/translation_table.h \ 
../avidemux/ADM_video/ADM_cache.h \ 
../avidemux/ADM_video/ADM_confCouple.h \ 
../avidemux/ADM_video/ADM_interlaced.h \ 
../avidemux/ADM_video/ADM_vidCached.h \ 
../avidemux/ADM_video/ADM_vidClean.h \ 
../avidemux/ADM_video/ADM_vidCNR2_param.h \ 
../avidemux/ADM_video/ADM_vidColorYuv.h \ 
../avidemux/ADM_video/ADM_vidColorYuv_param.h \ 
../avidemux/ADM_video/ADM_vidCommonFilter.h \ 
../avidemux/ADM_video/ADM_videoInfoExtractor.h \ 
../avidemux/ADM_video/ADM_videoNull.h \ 
../avidemux/ADM_video/ADM_vidEqualizer.h \ 
../avidemux/ADM_video/ADM_vidFieldUtil.h \ 
../avidemux/ADM_video/ADM_vidFont.h \ 
../avidemux/ADM_video/ADM_vidMPdelogo.h \ 
../avidemux/ADM_video/ADM_vidPartial.h \ 
../avidemux/ADM_video/ADM_vidPartial_param.h \ 
../avidemux/ADM_video/mmx_macros.h \ 
../avidemux/ADM_videoFilter/ADM_lavpp_deintparam.h \ 
../avidemux/ADM_videoFilter/ADM_mpdetc.h \ 
../avidemux/ADM_videoFilter/ADM_vidAddBorder.h \ 
../avidemux/ADM_videoFilter/ADM_vidAnimated.h \ 
../avidemux/ADM_videoFilter/ADM_vidAnimated_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidASharp_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidASS.h \ 
../avidemux/ADM_videoFilter/ADM_vidAss_Params.h \ 
../avidemux/ADM_videoFilter/ADM_vidBlendRemoval_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidChroma.h \ 
../avidemux/ADM_videoFilter/ADM_vidChromaShift.h \ 
../avidemux/ADM_videoFilter/ADM_vidChromaShift_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidComputeAverage.h \ 
../avidemux/ADM_videoFilter/ADM_vidContrast.h \ 
../avidemux/ADM_videoFilter/ADM_vidDecDec_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidDecTelecide.h \ 
../avidemux/ADM_videoFilter/ADM_vidDecTel_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidDeinterlace.h \ 
../avidemux/ADM_videoFilter/ADM_vidDenoise.h \ 
../avidemux/ADM_videoFilter/ADM_vidDGbob_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidDropOut.h \ 
../avidemux/ADM_videoFilter/ADM_vidDvbSub.h \ 
../avidemux/ADM_videoFilter/ADM_vidEq2.h \ 
../avidemux/ADM_videoFilter/ADM_vidEraser.h \ 
../avidemux/ADM_videoFilter/ADM_vidFade_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidField.h \ 
../avidemux/ADM_videoFilter/ADM_vidFlipV.h \ 
../avidemux/ADM_videoFilter/ADM_vidFlux.h \ 
../avidemux/ADM_videoFilter/ADM_vidForcedPP.h \ 
../avidemux/ADM_videoFilter/ADM_vidHue.h \ 
../avidemux/ADM_videoFilter/ADM_vidKernelDeint.h \ 
../avidemux/ADM_videoFilter/ADM_vidLargeMedian.h \ 
../avidemux/ADM_videoFilter/ADM_vidLuma.h \ 
../avidemux/ADM_videoFilter/ADM_vidMcDeint_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidMosaic_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidMPLD3D.h \ 
../avidemux/ADM_videoFilter/ADM_vidMPLD3Dlow.h \ 
../avidemux/ADM_videoFilter/ADM_vidMSharpen_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidMSmooth_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidPalShift.h \ 
../avidemux/ADM_videoFilter/ADM_vidPalSmart.h \ 
../avidemux/ADM_videoFilter/ADM_vidParticle.h \ 
../avidemux/ADM_videoFilter/ADM_vidPulldown.h \ 
../avidemux/ADM_videoFilter/ADM_vidSeparateField.h \ 
../avidemux/ADM_videoFilter/ADM_vidSoften.h \ 
../avidemux/ADM_videoFilter/ADM_vidSRT.h \ 
../avidemux/ADM_videoFilter/ADM_vidStabilize.h \ 
../avidemux/ADM_videoFilter/ADM_vidSwapFields.h \ 
../avidemux/ADM_videoFilter/ADM_vidSwapSmart.h \ 
../avidemux/ADM_videoFilter/ADM_vidSwissArmyKnife.h \ 
../avidemux/ADM_videoFilter/ADM_vidTDeint_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidThreshold.h \ 
../avidemux/ADM_videoFilter/ADM_vidUnblend_param.h \ 
../avidemux/ADM_videoFilter/ADM_vidUVSwap.h \ 
../avidemux/ADM_videoFilter/ADM_vidVlad.h \ 
../avidemux/ADM_videoFilter/ADM_vidVobSub.h \ 
../avidemux/ADM_videoFilter/ADM_vidVobSubBitmap.h \ 
../avidemux/ADM_videoFilter/ADM_vobsubinfo.h \ 
../avidemux/avi_vars.h \ 
../avidemux/gtkgui.h \ 
../avidemux/prefs.h \ 
../avidemux/prototype.h \ 

SOURCES = \
../avidemux/ADM_audio/ADM_a52info.cpp \ 
../avidemux/ADM_audio/ADM_aacinfo.cpp \ 
../avidemux/ADM_audio/ADM_dcainfo.cpp \ 
../avidemux/ADM_audio/ADM_mp3info.cpp \ 
../avidemux/ADM_audio/audioac3ex.cpp \ 
../avidemux/ADM_audio/audiogen.cpp \ 
../avidemux/ADM_audio/audiomp3ex.cpp \ 
../avidemux/ADM_audio/audiosource_ext.cpp \ 
../avidemux/ADM_audio/audiotimeline.cpp \ 
../avidemux/ADM_audio/audiowavex.cpp \ 
../avidemux/ADM_audio/audio_mpegidentify.cpp \ 
../avidemux/ADM_audio/audio_packetizer.cpp \ 
../avidemux/ADM_audiocodec/ADM_8bits.cpp \ 
../avidemux/ADM_audiocodec/ADM_audiocodec.cpp \ 
../avidemux/ADM_audiocodec/ADM_codecac3.cpp \ 
../avidemux/ADM_audiocodec/ADM_codecfaad.cpp \ 
../avidemux/ADM_audiocodec/ADM_codecimaadpcm.cpp \ 
../avidemux/ADM_audiocodec/ADM_codecmp3.cpp \ 
../avidemux/ADM_audiocodec/ADM_codecmsadpcm.cpp \ 
../avidemux/ADM_audiocodec/ADM_codeculaw.cpp \ 
../avidemux/ADM_audiocodec/ADM_codecwav.cpp \ 
../avidemux/ADM_audiocodec/ADM_codecwma.cpp \ 
../avidemux/ADM_audiocodec/ADM_dca.cpp \ 
../avidemux/ADM_audiocodec/ADM_lpcm.cpp \ 
../avidemux/ADM_audiocodec/audiocodec_ogg.cpp \ 
../avidemux/ADM_audiodevice/ADM_audiodevice.cpp \ 
../avidemux/ADM_audiodevice/ADM_deviceALSA.cpp \ 
../avidemux/ADM_audiodevice/ADM_deviceArts.cpp \ 
../avidemux/ADM_audiodevice/ADM_deviceAudioCore.cpp \ 
../avidemux/ADM_audiodevice/ADM_deviceEsd.cpp \ 
../avidemux/ADM_audiodevice/ADM_deviceJack.cpp \ 
../avidemux/ADM_audiodevice/ADM_deviceoss.cpp \ 
../avidemux/ADM_audiodevice/ADM_deviceSDL.cpp \ 
../avidemux/ADM_audiodevice/ADM_deviceWin32.cpp \ 
../avidemux/ADM_audiodevice/oss_out.cpp \ 
../avidemux/ADM_audiofilter/audiodeng_buildfilters.cpp \ 
../avidemux/ADM_audiofilter/audioencoder.cpp \ 
../avidemux/ADM_audiofilter/audioencoder_aften.cpp \ 
../avidemux/ADM_audiofilter/audioencoder_faac.cpp \ 
../avidemux/ADM_audiofilter/audioencoder_lame.cpp \ 
../avidemux/ADM_audiofilter/audioencoder_lavcodec.cpp \ 
../avidemux/ADM_audiofilter/audioencoder_pcm.cpp \ 
../avidemux/ADM_audiofilter/audioencoder_twolame.cpp \ 
../avidemux/ADM_audiofilter/audioencoder_vorbis.cpp \ 
../avidemux/ADM_audiofilter/audioeng_buff.cpp \ 
../avidemux/ADM_audiofilter/audioeng_process.cpp \ 
../avidemux/ADM_audiofilter/audiofilter_bridge.cpp \ 
../avidemux/ADM_audiofilter/audiofilter_buildchain.cpp \ 
../avidemux/ADM_audiofilter/audiofilter_channel_route.cpp \ 
../avidemux/ADM_audiofilter/audiofilter_dolby.cpp \ 
../avidemux/ADM_audiofilter/audiofilter_film2pal.cpp \ 
../avidemux/ADM_audiofilter/audiofilter_limiter.cpp \ 
../avidemux/ADM_audiofilter/audiofilter_mixer.cpp \ 
../avidemux/ADM_audiofilter/audiofilter_normalize.cpp \ 
../avidemux/ADM_audiofilter/audiofilter_sox.cpp \ 
../avidemux/ADM_audiofilter/audiolib_sox.cpp \ 
../avidemux/ADM_audiofilter/audio_raw.cpp \ 
../avidemux/ADM_codecs/ADM_codecs.cpp \ 
../avidemux/ADM_codecs/ADM_ffmp43.cpp \ 
../avidemux/ADM_codecs/ADM_ffmpeg.cpp \ 
../avidemux/ADM_codecs/ADM_mjpeg.cpp \ 
../avidemux/ADM_codecs/ADM_mjpegEncode.cpp \ 
../avidemux/ADM_codecs/ADM_mpeg.cpp \ 
../avidemux/ADM_codecs/ADM_png.cpp \ 
../avidemux/ADM_codecs/ADM_rgb16.cpp \ 
../avidemux/ADM_codecs/ADM_theora_dec.cpp \ 
../avidemux/ADM_codecs/ADM_uyvy.cpp \ 
../avidemux/ADM_codecs/ADM_x264.cpp \ 
../avidemux/ADM_codecs/ADM_xvid.cpp \ 
../avidemux/ADM_codecs/ADM_xvid4.cpp \ 
../avidemux/ADM_codecs/ADM_xvidcvs.cpp \ 
../avidemux/ADM_codecs/ADM_xvideco.cpp \ 
../avidemux/ADM_colorspace/ADM_colorspace.cpp \ 
../avidemux/ADM_colorspace/ADM_rgb.cpp \ 
../avidemux/ADM_colorspace/rgb2yuv.cpp \ 
../avidemux/ADM_colorspace/yuv.cpp \ 
../avidemux/ADM_editor/ADMedAVIAUD.cpp \ 
../avidemux/ADM_editor/ADM_edAudio.cpp \ 
../avidemux/ADM_editor/ADM_edCache.cpp \ 
../avidemux/ADM_editor/ADM_edFrameType.cpp \ 
../avidemux/ADM_editor/ADM_edIdentify.cpp \ 
../avidemux/ADM_editor/ADM_edit.cpp \ 
../avidemux/ADM_editor/ADM_edLoadSave.cpp \ 
../avidemux/ADM_editor/ADM_edRender.cpp \ 
../avidemux/ADM_editor/ADM_edSearch.cpp \ 
../avidemux/ADM_editor/ADM_edStub.cpp \ 
../avidemux/ADM_editor/ADM_Video.cpp \ 
../avidemux/ADM_encoder/adm_encConfig.cpp \ 
../avidemux/ADM_encoder/adm_encCopy.cpp \ 
../avidemux/ADM_encoder/adm_encdivx.cpp \ 
../avidemux/ADM_encoder/adm_encdivx2p.cpp \ 
../avidemux/ADM_encoder/adm_encffmpeg.cpp \ 
../avidemux/ADM_encoder/adm_encffmpeg1.cpp \ 
../avidemux/ADM_encoder/adm_encmjpeg.cpp \ 
../avidemux/ADM_encoder/adm_encmpeg2enc.cpp \ 
../avidemux/ADM_encoder/adm_encoder.cpp \ 
../avidemux/ADM_encoder/adm_encRequant.cpp \ 
../avidemux/ADM_encoder/adm_encx264.cpp \ 
../avidemux/ADM_encoder/adm_encxvid.cpp \ 
../avidemux/ADM_encoder/adm_encXvid4.cpp \ 
../avidemux/ADM_encoder/adm_encyv12.cpp \ 
../avidemux/ADM_filter/ADM_vidDummyFilter.cpp \ 
../avidemux/ADM_filter/filter.cpp \ 
../avidemux/ADM_filter/filter_declaration.cpp \ 
../avidemux/ADM_filter/filter_dylib.cpp \ 
../avidemux/ADM_filter/filter_saveload.cpp \ 
../avidemux/ADM_filter/vidVCD.cpp \ 
../avidemux/ADM_infoExtractor/ADM_infoextractor.cpp \ 
../avidemux/ADM_inputs/ADM_amv/ADM_amv.cpp \ 
../avidemux/ADM_inputs/ADM_amv/ADM_amvAudio.cpp \ 
../avidemux/ADM_inputs/ADM_asf/ADM_asf.cpp \ 
../avidemux/ADM_inputs/ADM_asf/ADM_asfChunk.cpp \ 
../avidemux/ADM_inputs/ADM_asf/ADM_asfPacket.cpp \ 
../avidemux/ADM_inputs/ADM_asf/ADM_asf_audio.cpp \ 
../avidemux/ADM_inputs/ADM_avsproxy/ADM_avsproxy.cpp \ 
../avidemux/ADM_inputs/ADM_avsproxy/ADM_avsproxy_net.cpp \ 
../avidemux/ADM_inputs/ADM_flv/ADM_flv.cpp \ 
../avidemux/ADM_inputs/ADM_flv/ADM_flvAudio.cpp \ 
../avidemux/ADM_inputs/ADM_flv/ADM_flvIndex.cpp \ 
../avidemux/ADM_inputs/ADM_h263/ADM_h263.cpp \ 
../avidemux/ADM_inputs/ADM_h263/ADM_mp4.cpp \ 
../avidemux/ADM_inputs/ADM_h263/bitsRead.cpp \ 
../avidemux/ADM_inputs/ADM_inpics/ADM_pics.cpp \ 
../avidemux/ADM_inputs/ADM_matroska/ADM_mkv.cpp \ 
../avidemux/ADM_inputs/ADM_matroska/ADM_mkvEntries.cpp \ 
../avidemux/ADM_inputs/ADM_matroska/ADM_mkvIndexer.cpp \ 
../avidemux/ADM_inputs/ADM_matroska/ADM_mkvTrackType.cpp \ 
../avidemux/ADM_inputs/ADM_matroska/ADM_mkv_audio.cpp \ 
../avidemux/ADM_inputs/ADM_matroska/ebml.cpp \ 
../avidemux/ADM_inputs/ADM_matroska/mkv_tags.cpp \ 
../avidemux/ADM_inputs/ADM_mp4/ADM_atom.cpp \ 
../avidemux/ADM_inputs/ADM_mp4/ADM_mp4.cpp \ 
../avidemux/ADM_inputs/ADM_mp4/ADM_mp4Analyzer.cpp \ 
../avidemux/ADM_inputs/ADM_mp4/ADM_mp4audio.cpp \ 
../avidemux/ADM_inputs/ADM_mp4/ADM_mp4Indexer.cpp \ 
../avidemux/ADM_inputs/ADM_mp4/ADM_mp4Leaf.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_audio.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_demuxer.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_demuxerES.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_demuxerMSDVR.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_demuxerPS.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_demuxerTS.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_identify.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_indexer.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_indexer_h264.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_indexer_mpeg2.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_io.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_probe.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_probeTS.cpp \ 
../avidemux/ADM_inputs/ADM_mpegdemuxer/dmx_video.cpp \ 
../avidemux/ADM_inputs/ADM_nuv/ADM_nuv.cpp \ 
../avidemux/ADM_inputs/ADM_nuv/ADM_nuvAudio.cpp \ 
../avidemux/ADM_inputs/ADM_nuv/RTjpegN.cpp \ 
../avidemux/ADM_inputs/ADM_nuv/RToldformat.cpp \ 
../avidemux/ADM_inputs/ADM_ogm/ADM_ogm.cpp \ 
../avidemux/ADM_inputs/ADM_ogm/ADM_ogmAudio.cpp \ 
../avidemux/ADM_inputs/ADM_ogm/ADM_ogmpages.cpp \ 
../avidemux/ADM_inputs/ADM_ogm/ADM_ogmreorder.cpp \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_odml_audio.cpp \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_odml_odml.cpp \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_odml_regular.cpp \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_openDML.cpp \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_openDMLDepack.cpp \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_opendml_reindex.cpp \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_opendml_reorder.cpp \ 
../avidemux/ADM_inputs/ADM_openDML/ADM_riff.cpp \ 
../avidemux/ADM_libraries/ADM_lavformat/ADM_lavformat.cpp \ 
../avidemux/ADM_libraries/ADM_lavformat/ADM_muxts.cpp \ 
../avidemux/ADM_libraries/ADM_libmpeg2enc/ADM_mpe2enc.cpp \ 
../avidemux/ADM_libraries/ADM_libswscale/ADM_mp.cpp \ 
../avidemux/ADM_libraries/ADM_libwrapper/libwrapper.cpp \ 
../avidemux/ADM_libraries/ADM_libwrapper/libwrapper_amrnb.cpp \ 
../avidemux/ADM_libraries/ADM_libwrapper/libwrapper_dca.cpp \ 
../avidemux/ADM_libraries/ADM_libwrapper/libwrapper_global.cpp \ 
../avidemux/ADM_libraries/ADM_lvemux/ADM_muxer.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/ac3strm_in.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/ADM_mplexin.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/ADM_mplexmuxer.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/ADM_mplexout.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/ADM_mthread.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/ADM_transfert.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/audiostrm_out.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/bits.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/decodebufmodel.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/dtsstrm_in.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/inputstrm.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/interact.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/lpcmstrm_in.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/mpastrm_in.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/multiplexor.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/padstrm.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/stillsstream.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/stream_params.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/systems.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/videostrm_in.cpp \ 
../avidemux/ADM_libraries/ADM_mplex/videostrm_out.cpp \ 
../avidemux/ADM_libraries/ADM_nvwa/debug_new.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_bitstream.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_fileio.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_gettext.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_image.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_imageLoader.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_imageResizer.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_imageUtils.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_pp.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/ADM_print.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/avidemutils.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/aviframe.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/aviindexer.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/aviio.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/broken.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/fourcc.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/prefs.cpp \ 
../avidemux/ADM_libraries/ADM_utilities/subchunk.cpp \ 
../avidemux/ADM_libraries/ADM_xvidratectl/ADM_oldxvid.cpp \ 
../avidemux/ADM_libraries/ADM_xvidratectl/ADM_xvidratectl.cpp \ 
../avidemux/ADM_libraries/ADM_xvidratectl/ADM_xvidratectlVBV.cpp \ 
../avidemux/ADM_ocr/ADM_bitmapSource.cpp \ 
../avidemux/ADM_ocr/adm_glyph.cpp \ 
../avidemux/ADM_ocr/adm_leftturn.cpp \ 
../avidemux/ADM_ocr/ADM_ocr.cpp \ 
../avidemux/ADM_ocr/ADM_ocrEngine.cpp \ 
../avidemux/ADM_ocr/ADM_vob2vobsub.cpp \ 
../avidemux/ADM_osSupport/ADM_cpuCap.cpp \ 
../avidemux/ADM_osSupport/ADM_crashdump.cpp \ 
../avidemux/ADM_osSupport/ADM_debug.cpp \ 
../avidemux/ADM_osSupport/ADM_fileio.cpp \ 
../avidemux/ADM_osSupport/ADM_memcpy.cpp \ 
../avidemux/ADM_osSupport/ADM_memory.cpp \ 
../avidemux/ADM_osSupport/ADM_memsupport.cpp \ 
../avidemux/ADM_osSupport/ADM_misc.cpp \ 
../avidemux/ADM_osSupport/ADM_queue.cpp \ 
../avidemux/ADM_osSupport/ADM_quota.cpp \ 
../avidemux/ADM_osSupport/ADM_threads.cpp \ 
../avidemux/ADM_osSupport/TLK_clock.cpp \ 
../avidemux/ADM_osSupport/win32.cpp \ 
../avidemux/ADM_outputs/oplug_avi/avilist.cpp \ 
../avidemux/ADM_outputs/oplug_avi/op_avisave.cpp \ 
../avidemux/ADM_outputs/oplug_avi/op_avisavecopy.cpp \ 
../avidemux/ADM_outputs/oplug_avi/op_avisavecopy_pack.cpp \ 
../avidemux/ADM_outputs/oplug_avi/op_avisavecopy_unpack.cpp \ 
../avidemux/ADM_outputs/oplug_avi/op_avisavedual.cpp \ 
../avidemux/ADM_outputs/oplug_avi/op_aviwrite.cpp \ 
../avidemux/ADM_outputs/oplug_avi/op_saveprocess.cpp \ 
../avidemux/ADM_outputs/oplug_avi/op_savesmart.cpp \ 
../avidemux/ADM_outputs/oplug_dummy/oplug_dummy.cpp \ 
../avidemux/ADM_outputs/oplug_flv/oplug_flv.cpp \ 
../avidemux/ADM_outputs/oplug_mp4/oplug_mp4.cpp \ 
../avidemux/ADM_outputs/oplug_mpeg/op_mpegpass.cpp \ 
../avidemux/ADM_outputs/oplug_mpegFF/oplug_vcdff.cpp \ 
../avidemux/ADM_outputs/oplug_ogm/op_ogaudio.cpp \ 
../avidemux/ADM_outputs/oplug_ogm/op_ogpage.cpp \ 
../avidemux/ADM_outputs/oplug_ogm/op_ogsave.cpp \ 
../avidemux/ADM_outputs/oplug_ogm/op_ogsavecopy.cpp \ 
../avidemux/ADM_outputs/oplug_ogm/op_ogsaveprocess.cpp \ 
../avidemux/ADM_preview.cpp \ 
../avidemux/ADM_script/ADM_Avidemux.cpp \ 
../avidemux/ADM_script/ADM_AvidemuxAudio.cpp \ 
../avidemux/ADM_script/ADM_AvidemuxVideo.cpp \ 
../avidemux/ADM_script/ADM_JSAvidemux.cpp \ 
../avidemux/ADM_script/ADM_JSAvidemuxAudio.cpp \ 
../avidemux/ADM_script/ADM_JSAvidemuxVideo.cpp \ 
../avidemux/ADM_script/ADM_JSDirectorySearch.cpp \ 
../avidemux/ADM_script/ADM_JSFunctions.cpp \ 
../avidemux/ADM_script/ADM_JSGlobal.cpp \ 
../avidemux/ADM_script/DirectorySearch.cpp \ 
../avidemux/ADM_toolkit/ADM_audioQueue.cpp \ 
../avidemux/ADM_toolkit/ADM_intfloat.cpp \ 
../avidemux/ADM_toolkit/ADM_packetQueue.cpp \ 
../avidemux/ADM_toolkit/automation.cpp \ 
../avidemux/ADM_toolkit/filesel.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_animated.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_audioconfig.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_audioFilter.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_bitrateHisto.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_builtin.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_DVDff.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_enter.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flv1.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyAsharp.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyChromaShift.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyContrast.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyCrop.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyDialog.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyEq2.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyEraser.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyHue.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyParticle.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flySrtPos.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flySwissArmyKnife.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_flyThreshold.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_gototime.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_jobs_save.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_lavcodec.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_lavDecoder.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_mjpeg.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_ocr.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_postproc.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_prefs.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_requant.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_resizeWiz.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_srt.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_SVCD.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_tdeint.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_tsSub.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/DIA_v2v.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/GUI_render.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/GUI_sdlRender.cpp \ 
../avidemux/ADM_userInterfaces/ADM_commonUI/GUI_xvRender.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/alert_qt4.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/DIA_busy.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/DIA_none.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/DIA_srt.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/DIA_x264.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/DIA_xvid4.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/OCR_none.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_about.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_asharp.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_calculator.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_chromashift.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_contrast.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_crop.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_encoding.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_eq2.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_hue.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_jobs.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_license.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_props.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_resizing.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_srt.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_vobsub.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/Q_working.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/T_flyDialog.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/T_index_pg.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/T_QCanvas.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/FAC_bar.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/FAC_float.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/FAC_frame.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/FAC_hex.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/FAC_integer.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/FAC_matrix.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/FAC_notch.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/FAC_readOnlyText.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/T_bitrate.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/T_button.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/T_dialogFactory.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/T_filesel.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/T_menu.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/T_slider.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/T_threadCount.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialogFactory/T_toggle.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_filters/filter_none.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_filters/Q_mainfilter.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_gui/ADM_qslider.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_gui/file_qt4.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_gui/gui_none.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_gui/Q_gui2.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_gui/T_preview.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_ocr/Q_ocr.cpp \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ui_support.cpp \ 
../avidemux/ADM_video/ADM_cache.cpp \ 
../avidemux/ADM_video/ADM_confCouples.cpp \ 
../avidemux/ADM_video/ADM_genvideo.cpp \ 
../avidemux/ADM_video/ADM_interlaced.cpp \ 
../avidemux/ADM_video/ADM_reorderTemplate.cpp \ 
../avidemux/ADM_video/ADM_vidCached.cpp \ 
../avidemux/ADM_video/ADM_vidClean.cpp \ 
../avidemux/ADM_video/ADM_vidCNR2.cpp \ 
../avidemux/ADM_video/ADM_vidColorYuv.cpp \ 
../avidemux/ADM_video/ADM_vidEqualizer.cpp \ 
../avidemux/ADM_video/ADM_vidFieldUnblend.cpp \ 
../avidemux/ADM_video/ADM_vidFieldUtil.cpp \ 
../avidemux/ADM_video/ADM_vidFont.cpp \ 
../avidemux/ADM_video/ADM_vidMPdelogo.cpp \ 
../avidemux/ADM_video/ADM_vidNull.cpp \ 
../avidemux/ADM_video/ADM_vidPartial.cpp \ 
../avidemux/ADM_video/ADM_vidRaw.cpp \ 
../avidemux/ADM_videoFilter/ADMmpdetc.cpp \ 
../avidemux/ADM_videoFilter/ADM_guiResize.cpp \ 
../avidemux/ADM_videoFilter/ADM_lavpp_deint.cpp \ 
../avidemux/ADM_videoFilter/ADM_resizebis.cpp \ 
../avidemux/ADM_videoFilter/ADM_resizeter.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidAddBorder.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidAnimated.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidAsharp.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidASS.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidBlend.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidBlendRemoval.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidBSmear.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidChroma.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidChromaShift.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidComputeAverage.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidContrast.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidCrop.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidDecDec.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidDecTelecide.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidDeintASM.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidDeinterlace.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidDelta.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidDenoise.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidDGbob.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidDropOut.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidDvbSub.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidEq2.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidEraser.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidFade.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidFastConvolution.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidFields.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidFlipV.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidFlux.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidForcedPP.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidHardIvtcRemoval.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidHue.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidKernelDeint.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidLargeMedian.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidLogo.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidLuma.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidMcDeint.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidMosaic.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidMPLD3D.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidMPLD3Dlow.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidMPLResize.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidMSharpen.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidMsmooth.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidPalShift.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidPalSmart.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidParticle.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidPulldown.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidResampleFPS.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidResize.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidResize25.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidReverse.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidRotate.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidSeparateField.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidSoften.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidSRT.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidSRTload.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidSRTRender.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidStabilize.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidSwapFields.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidSwapSmart.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidSwissArmyKnife.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidTdeint.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidThreshold.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidUnblend.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidUVSwap.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidVlad.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidVobsub.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidVobSubRender.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidWhirl.cpp \ 
../avidemux/ADM_videoFilter/ADM_vidYadif.cpp \ 
../avidemux/ADM_videoFilter/ADM_vobsubinfo.cpp \ 
../avidemux/gtk_gui.cpp \ 
../avidemux/guiplay.cpp \ 
../avidemux/gui_action.cpp \ 
../avidemux/gui_autodrive.cpp \ 
../avidemux/GUI_jobs.cpp \ 
../avidemux/gui_navigate.cpp \ 
../avidemux/gui_savenew.cpp \ 
../avidemux/main.cpp \ 

FORMS = \
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/about.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/asharp.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/calculator.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/chromashift.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/contrast.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/crop.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/encoding.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/eq2.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/hue.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/jobs.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/license.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/props.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/resizing.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/srt.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/vobsub.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_dialog/working.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_filters/mainfilter.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_gui/gui2.ui \ 
../avidemux/ADM_userInterfaces/ADM_QT4/ADM_ocr/ocr.ui \ 

TRANSLATIONS = \
./avidemux_ca.ts \ 
./avidemux_cs.ts \ 
./avidemux_de.ts \ 
./avidemux_el.ts \ 
./avidemux_es.ts \ 
./avidemux_fr.ts \ 
./avidemux_it.ts \ 
./avidemux_ja.ts \ 
./avidemux_pt_BR.ts \ 
./avidemux_ru.ts \ 
./avidemux_sr.ts \ 
./avidemux_sr@latin.ts \ 
./avidemux_tr.ts \ 

