// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList fitToSize_param[]={
 {"width",offsetof(fitToSize,width),"uint32_t",ADM_param_uint32_t},
 {"height",offsetof(fitToSize,height),"uint32_t",ADM_param_uint32_t},
 {"algo",offsetof(fitToSize,algo),"uint32_t",ADM_param_uint32_t},
 {"roundup",offsetof(fitToSize,roundup),"uint32_t",ADM_param_uint32_t},
 {"pad",offsetof(fitToSize,pad),"uint32_t",ADM_param_uint32_t},
 {"tolerance",offsetof(fitToSize,tolerance),"float",ADM_param_float},
{NULL,0,NULL}
};
