// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "contrast.h"
bool  contrast_jserialize(const char *file, const contrast *key){
admJson json;
json.addFloat("coef",key->coef);
json.addInt32("offset",key->offset);
json.addBool("doLuma",key->doLuma);
json.addBool("doChromaU",key->doChromaU);
json.addBool("doChromaV",key->doChromaV);
return json.dumpToFile(file);
};
bool  contrast_jdeserialize(const char *file, const ADM_paramList *tmpl,contrast *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
