// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList contrast_param[]={
 {"coef",offsetof(contrast,coef),"float",ADM_param_float},
 {"offset",offsetof(contrast,offset),"int32_t",ADM_param_int32_t},
 {"doLuma",offsetof(contrast,doLuma),"bool",ADM_param_bool},
 {"doChromaU",offsetof(contrast,doChromaU),"bool",ADM_param_bool},
 {"doChromaV",offsetof(contrast,doChromaV),"bool",ADM_param_bool},
{NULL,0,NULL}
};
