// automatically generated by admSerialization.py do not edit
#ifndef ADM_fade_CONF_H
#define ADM_fade_CONF_H
typedef struct {
uint32_t startFade;
uint32_t endFade;
bool inOut;
bool toBlack;
}fade;
#endif
