// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList ffvaenc_encoder_param[]={
 {"preset",offsetof(ffvaenc_encoder,preset),"uint32_t",ADM_param_uint32_t},
 {"bitrate",offsetof(ffvaenc_encoder,bitrate),"uint32_t",ADM_param_uint32_t},
 {"max_bitrate",offsetof(ffvaenc_encoder,max_bitrate),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
