// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
uint32_t profile;
uint32_t gopsize;
uint32_t bframes;
uint32_t bitrate;
uint32_t max_bitrate;
uint32_t quality;
uint32_t rc_mode;
}ffvaenc_encoder;
