// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList ffnvenc_encoder_param[]={
 {"preset",offsetof(ffnvenc_encoder,preset),"uint32_t",ADM_param_uint32_t},
 {"profile",offsetof(ffnvenc_encoder,profile),"uint32_t",ADM_param_uint32_t},
 {"rc_mode",offsetof(ffnvenc_encoder,rc_mode),"uint32_t",ADM_param_uint32_t},
 {"quality",offsetof(ffnvenc_encoder,quality),"uint32_t",ADM_param_uint32_t},
 {"bitrate",offsetof(ffnvenc_encoder,bitrate),"uint32_t",ADM_param_uint32_t},
 {"max_bitrate",offsetof(ffnvenc_encoder,max_bitrate),"uint32_t",ADM_param_uint32_t},
 {"gopsize",offsetof(ffnvenc_encoder,gopsize),"uint32_t",ADM_param_uint32_t},
 {"bframes",offsetof(ffnvenc_encoder,bframes),"uint32_t",ADM_param_uint32_t},
 {"b_ref_mode",offsetof(ffnvenc_encoder,b_ref_mode),"uint32_t",ADM_param_uint32_t},
 {"lookahead",offsetof(ffnvenc_encoder,lookahead),"uint32_t",ADM_param_uint32_t},
 {"aq_strength",offsetof(ffnvenc_encoder,aq_strength),"uint32_t",ADM_param_uint32_t},
 {"spatial_aq",offsetof(ffnvenc_encoder,spatial_aq),"bool",ADM_param_bool},
 {"temporal_aq",offsetof(ffnvenc_encoder,temporal_aq),"bool",ADM_param_bool},
 {"weighted_pred",offsetof(ffnvenc_encoder,weighted_pred),"bool",ADM_param_bool},
{NULL,0,NULL}
};
