// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList ffnvenc_encoder_param[]={
 {"preset",offsetof(ffnvenc_encoder,preset),"uint32_t",ADM_param_uint32_t},
 {"profile",offsetof(ffnvenc_encoder,profile),"uint32_t",ADM_param_uint32_t},
 {"gopsize",offsetof(ffnvenc_encoder,gopsize),"uint32_t",ADM_param_uint32_t},
 {"bframes",offsetof(ffnvenc_encoder,bframes),"uint32_t",ADM_param_uint32_t},
 {"bitrate",offsetof(ffnvenc_encoder,bitrate),"uint32_t",ADM_param_uint32_t},
 {"max_bitrate",offsetof(ffnvenc_encoder,max_bitrate),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
