// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
uint32_t preset;
uint32_t profile;
uint32_t rc_mode;
uint32_t quality;
uint32_t bitrate;
uint32_t max_bitrate;
uint32_t gopsize;
uint32_t bframes;
uint32_t b_ref_mode;
uint32_t lookahead;
uint32_t aq_strength;
bool spatial_aq;
bool temporal_aq;
bool weighted_pred;
}ffnvenc_encoder;
