// automatically generated by admSerialization.py do not edit
#ifndef ADM_ts_muxer_CONF_H
#define ADM_ts_muxer_CONF_H
typedef struct {
bool acceptNonCompliant;
bool vbr;
uint32_t muxRateInMBits;
}ts_muxer;
#endif
