// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList utvideo_encoder_param[]={
 {"prediction",offsetof(utvideo_encoder,prediction),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
