// automatically generated by admSerialization.py do not edit
#ifndef ADM_artVHS_CONF_H
#define ADM_artVHS_CONF_H
typedef struct {
float lumaBW;
float chromaBW;
bool lumaNoDelay;
bool chromaNoDelay;
float unSync;
}artVHS;
#endif
