// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList artVHS_param[]={
 {"lumaBW",offsetof(artVHS,lumaBW),"float",ADM_param_float},
 {"chromaBW",offsetof(artVHS,chromaBW),"float",ADM_param_float},
 {"lumaNoDelay",offsetof(artVHS,lumaNoDelay),"bool",ADM_param_bool},
 {"chromaNoDelay",offsetof(artVHS,chromaNoDelay),"bool",ADM_param_bool},
 {"unSync",offsetof(artVHS,unSync),"float",ADM_param_float},
 {"unSyncFilter",offsetof(artVHS,unSyncFilter),"float",ADM_param_float},
{NULL,0,NULL}
};
