// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
float lumaBW;
float chromaBW;
bool lumaNoDelay;
bool chromaNoDelay;
float unSync;
float unSyncFilter;
float noise;
}artVHS;
