// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "vaenc_settings.h"
bool  vaconf_settings_jserialize(const char *file, const vaconf_settings *key){
admJson json;
json.addUint32("BitrateKbps",key->BitrateKbps);
json.addUint32("IntraPeriod",key->IntraPeriod);
return json.dumpToFile(file);
};
bool  vaconf_settings_jdeserialize(const char *file, const ADM_paramList *tmpl,vaconf_settings *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
