// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList vaconf_settings_param[]={
 {"BitrateKbps",offsetof(vaconf_settings,BitrateKbps),"uint32_t",ADM_param_uint32_t},
 {"IntraPeriod",offsetof(vaconf_settings,IntraPeriod),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
