// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList artChromaKey_param[]={
 {"c1en",offsetof(artChromaKey,c1en),"bool",ADM_param_bool},
 {"c1u",offsetof(artChromaKey,c1u),"float",ADM_param_float},
 {"c1v",offsetof(artChromaKey,c1v),"float",ADM_param_float},
 {"c1dist",offsetof(artChromaKey,c1dist),"float",ADM_param_float},
 {"c1slope",offsetof(artChromaKey,c1slope),"float",ADM_param_float},
 {"c2en",offsetof(artChromaKey,c2en),"bool",ADM_param_bool},
 {"c2u",offsetof(artChromaKey,c2u),"float",ADM_param_float},
 {"c2v",offsetof(artChromaKey,c2v),"float",ADM_param_float},
 {"c2dist",offsetof(artChromaKey,c2dist),"float",ADM_param_float},
 {"c2slope",offsetof(artChromaKey,c2slope),"float",ADM_param_float},
 {"c3en",offsetof(artChromaKey,c3en),"bool",ADM_param_bool},
 {"c3u",offsetof(artChromaKey,c3u),"float",ADM_param_float},
 {"c3v",offsetof(artChromaKey,c3v),"float",ADM_param_float},
 {"c3dist",offsetof(artChromaKey,c3dist),"float",ADM_param_float},
 {"c3slope",offsetof(artChromaKey,c3slope),"float",ADM_param_float},
 {"spill",offsetof(artChromaKey,spill),"uint32_t",ADM_param_uint32_t},
 {"imagefile",offsetof(artChromaKey,imagefile),"std::string",ADM_param_stdstring},
{NULL,0,NULL}
};
