// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList negative_param[]={
 {"invertY",offsetof(negative,invertY),"bool",ADM_param_bool},
 {"invertU",offsetof(negative,invertU),"bool",ADM_param_bool},
 {"invertV",offsetof(negative,invertV),"bool",ADM_param_bool},
{NULL,0,NULL}
};
