// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList cubicLUT_param[]={
 {"lutfile",offsetof(cubicLUT,lutfile),"std::string",ADM_param_stdstring},
 {"hald",offsetof(cubicLUT,hald),"bool",ADM_param_bool},
{NULL,0,NULL}
};
