// automatically generated by admSerialization.py do not edit
#ifndef ADM_lame_encoder_CONF_H
#define ADM_lame_encoder_CONF_H
typedef struct {
uint32_t bitrate;
uint32_t preset;
uint32_t quality;
bool disableBitReservoir;
}lame_encoder;
#endif
