// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList artPosterize_param[]={
 {"levels",offsetof(artPosterize,levels),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
