// automatically generated by admSerialization.py, do not edit!
// automatically generated by admSerialization.py do not edit
#ifndef ADM_swresize_CONF_H
#define ADM_swresize_CONF_H
typedef struct {
uint32_t width;
uint32_t height;
uint32_t algo;
uint32_t sourceAR;
uint32_t targetAR;
}swresize;
#endif
