#
#
#
MACRO(ADM_PREBUILD)
        LIST(APPEND PlatformLibs   "-lm -lstdc++")
ENDMACRO(ADM_PREBUILD)
#
#
#
MACRO(ADM_MAIN_APP)
        ADD_EXECUTABLE(avidemux3_cli   ${ADM_EXE_SRCS})
ENDMACRO(ADM_MAIN_APP)
#

MACRO(ADM_POSTBUILD)
	ADM_INSTALL_BIN(avidemux3_cli)
ENDMACRO(ADM_POSTBUILD)
