include(admAsNeeded)
include(admPluginLocation)
#
MACRO(INIT_AUDIO_PLUGIN _lib)
  INCLUDE_DIRECTORIES("${ADM_HEADER_DIR}/ADM_audioCodec")
ENDMACRO()
#
MACRO(INSTALL_AUDIODECODER _lib)
  IF(NOT MSVC)
    SET(EXTRALIB "m")
  ENDIF(NOT MSVC)

  TARGET_LINK_LIBRARIES(${_lib} PRIVATE ADM_core6 ${EXTRALIB})
  INSTALL(TARGETS ${_lib}
  DESTINATION "${AVIDEMUX_LIB_DIR}/${ADM_PLUGIN_DIR}/audioDecoder/"
  COMPONENT  plugins
  )
ENDMACRO()
# # # ########### ADD_VIDEO_FILTER ###################"
MACRO(ADD_AUDIO_DECODER name)
  ADM_ADD_SHARED_LIBRARY(${name} ${ARGN})
ENDMACRO()

