include(admAsNeeded)
MACRO(INIT_AUDIO_PLUGIN _lib)
	INCLUDE_DIRECTORIES("${AVIDEMUX_TOP_SOURCE_DIR}/avidemux/common/ADM_audiocodec")
ENDMACRO(INIT_AUDIO_PLUGIN)

MACRO(INSTALL_AUDIODECODER _lib)
	TARGET_LINK_LIBRARIES(${_lib} ADM_core6 )
	INSTALL(TARGETS ${_lib} DESTINATION "${AVIDEMUX_LIB_DIR}/${ADM_PLUGIN_DIR}/audioDecoder/")
ENDMACRO(INSTALL_AUDIODECODER)
############## ADD_VIDEO_FILTER ###################"
MACRO(ADD_AUDIO_DECODER name)
        ADD_LIBRARY(${name} SHARED ${ARGN})
	AS_NEEDED(${name})
ENDMACRO(ADD_AUDIO_DECODER name)

