MACRO(checkXvid)
		OPTION(XVID "" ON)

		MESSAGE(STATUS "Checking for Xvid")
		MESSAGE(STATUS "*****************")

		IF (XVID)
			FIND_HEADER_AND_LIB(XVID xvid.h xvidcore xvid_plugin_single)
			PRINT_LIBRARY_INFO("Xvid" XVID_FOUND "${XVID_INCLUDE_DIR}" "${XVID_LIBRARY_DIR}")
                        SET(USE_XVID 1)
		ELSE (XVID)
			MESSAGE("${MSG_DISABLE_OPTION}")
                        SET(XVID_INCLUDE_DIR "")
                        SET(XVID_LIBRARY_DIR "")
		ENDIF (XVID)
		MESSAGE("")
ENDMACRO(checkXvid)
