MACRO(checkGlade)
	IF (NOT GLADE_CHECKED)
		OPTION(GLADE "" ON)

		MESSAGE(STATUS "Checking for glade-2.0")
		MESSAGE(STATUS "**********************")

		IF (GLADE)
			PKG_CHECK_MODULES(GLADE libglade-2.0)
			PRINT_LIBRARY_INFO("LibGlade" GLADE_FOUND "${GLADE_CFLAGS}" "${GLADE_LDFLAGS}")
		ELSE (GLADE)
			MESSAGE("${MSG_DISABLE_OPTION}")
		ENDIF (GLADE)

		SET(GLADE_CHECKED 1)

		MESSAGE("")
	ENDIF (NOT GLADE_CHECKED)
ENDMACRO(checkGlade)