MACRO(checkNvEnc)
	IF (NOT NVENC_CHECKED)
		OPTION(NVENC "" ON)

		MESSAGE(STATUS "Checking for NVENC")
		MESSAGE(STATUS "*****************")

		IF (NVENC)
            PKG_CHECK_MODULES(FFNVENC ffnvcodec)
		    IF (FFNVENC_FOUND)
                        IF(FFNVENC_INCLUDE_DIRS)
                            MESSAGE(STATUS " nvenc header Found in ${FFNVENC_INCLUDE_DIRS}")
                            SET(USE_NVENC True)
                            SET(NVENC_FOUND 1)
                        ELSE(FFNVENC_INCLUDE_DIRS)
                            MESSAGE(STATUS " nvenc header not Found ")
                            SET(NVENC_FOUND 0)
                        ENDIF(FFNVENC_INCLUDE_DIRS)
		        SET(NVENC_CHECKED 1)
		    ELSE (FFNVENC_FOUND)
                MESSAGE(STATUS "FFNVENC not found, you can get it from here https://github.com/FFmpeg/nv-codec-headers")
		    ENDIF (FFNVENC_FOUND)
		ENDIF (NVENC)

		MESSAGE("")
	APPEND_SUMMARY_LIST("Video Encoder" "NVENC" "${NVENC_FOUND}")
	ENDIF (NOT NVENC_CHECKED)

ENDMACRO(checkNvEnc)
