#
#
include(debianArch)
include(admTimeStamp)
#
SET (CPACK_GENERATOR "DEB")
# ARCH
SET_DEBIAN_ARCH()
# Mandatory
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "mean")

SET(CPACK_SET_DESTDIR "ON")

#
SET(CPACK_DEBIAN_PACKAGE_SECTION "extra")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
#
SET(CPACK_PACKAGE_NAME "${CPACK_DEBIAN_PACKAGE_NAME}")

#
#
ADM_TIMESTAMP(date)
SET(CPACK_PACKAGE_FILE_NAME  "${CPACK_PACKAGE_NAME}-${AVIDEMUX_VERSION}-${date}")

include(CPack)
