MACRO(checkAomDec)
    OPTION(AOMDEC "" ON)

    MESSAGE(STATUS "Checking for libaom")
    MESSAGE(STATUS "*****************")

    IF (AOMDEC)
        PKG_CHECK_MODULES(AOM aom)
        IF (${AOM_FOUND})
#           ADM_CHECK_FUNCTION_EXISTS(aom_codec_dec_init_ver "${AOM_LIBRARY_DIRS}" AOM_DEC_INIT_FOUND "" -I"${AOM_INCLUDE_DIRS}")
            PRINT_LIBRARY_INFO("libaom" AOM_FOUND "${AOM_INCLUDE_DIRS}" "${AOM_LIBRARY_DIRS}")
            SET(USE_AOM 1)
        ENDIF (${AOM_FOUND})
#       IF (${AOM_FOUND} AND ${AOM_DEC_INIT_FOUND})
#           SET(USE_AOM 1)
#           MESSAGE(STATUS "Linking to AOM decoder library")
#       ELSE (${AOM_FOUND} AND ${AOM_DEC_INIT_FOUND})
#           MESSAGE("${MSG_DISABLE_OPTION}")
#       ENDIF (${AOM_FOUND} AND ${AOM_DEC_INIT_FOUND})
    ENDIF (AOMDEC)
    MESSAGE("")

    APPEND_SUMMARY_LIST("Video Decoder" "libaom" "${AOM_FOUND}")
ENDMACRO(checkAomDec)
