MACRO(INIT_DEMUXER _lib)
ENDMACRO(INIT_DEMUXER)

MACRO(INSTALL_DEMUXER _lib)
        TARGET_LINK_LIBRARIES(${_lib} ADM_core ADM_coreUtils ADM_coreAudio ADM_coreImage ADM_coreUI ADM_core ADM_coreDemuxer)
	INSTALL(TARGETS ${_lib} DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/ADM_plugins6/demuxers/")
ENDMACRO(INSTALL_DEMUXER)
