# Find arts CFLAGS etc

FIND_PROGRAM(ARTS_CONFIG_EXECUTABLE artsc-config)
MARK_AS_ADVANCED(ARTS_CONFIG_EXECUTABLE)

IF (ARTS_CONFIG_EXECUTABLE)
    EXECUTE_PROCESS(COMMAND ${ARTS_CONFIG_EXECUTABLE} --cflags
      OUTPUT_VARIABLE ARTS_CFLAGS
      OUTPUT_STRIP_TRAILING_WHITESPACE)
      
    EXECUTE_PROCESS(COMMAND ${ARTS_CONFIG_EXECUTABLE} --libs
      OUTPUT_VARIABLE ARTS_LDFLAGS
      OUTPUT_STRIP_TRAILING_WHITESPACE)

    SET(ARTS_FOUND TRUE)
ENDIF(ARTS_CONFIG_EXECUTABLE)
