MACRO(INIT_MUXER _lib)
ENDMACRO(INIT_MUXER)

MACRO(INSTALL_MUXER _lib)
        TARGET_LINK_LIBRARIES(${_lib} ADM_core ADM_coreUtils ADM_coreAudio ADM_coreImage ADM_coreUI ADM_core ADM_coreMuxer)
	INSTALL(TARGETS ${_lib} DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/ADM_plugins6/muxers/")
ENDMACRO(INSTALL_MUXER)
