include(plugin_qt4)
include(admAsNeeded)
include(admOpenGl)    
MACRO(INIT_VIDEO_FILTER_GLQT4  lib  _srcsQt _headersQt _srcQt_ui  )
                ADM_ADD_QT_INCLUDE_DIR(${QT_EXTENSION} ADM_openGL)
                ADM_ADD_QT_INCLUDE_DIR(${QT_EXTENSION} ADM_UIs)
                IF("${_srcQt_ui}" STREQUAL "")
                        # No ui file
                ELSE("${_srcQt_ui}" STREQUAL "")
		        ADM_QT_WRAP_UI(qt4_ui ${_srcQt_ui}.ui)
                ENDIF("${_srcQt_ui}" STREQUAL "")
		ADM_QT_WRAP_CPP(qt4_cpp ${_headersQt})

		ADD_LIBRARY(${lib} SHARED ${ARGN} ${_srcsQt} ${qt4_cpp} ${qt4_ui})
		AS_NEEDED(${lib})
		ADM_TARGET_NO_EXCEPTION(${lib})
		ADD_TARGET_CFLAGS(${lib} "-DADM_UI_TYPE_BUILD=4")
		TARGET_LINK_LIBRARIES( ${lib} ADM_UI${QT_LIBRARY_EXTENSION}6  ADM_render6_${QT_LIBRARY_EXTENSION} )
                ADM_OPEN_GL(${lib})
		INIT_VIDEO_FILTER_INTERNAL(${lib})
		INSTALL_VIDEO_FILTER_INTERNAL(${lib} ${QT_EXTENSION})
ENDMACRO(INIT_VIDEO_FILTER_GLQT4)
