#
#
#
MACRO(ADM_PREBUILD)
        LIST(APPEND PlatformLibs   "-lm -lstdc++")
        LIST(APPEND PlatformLibs   "X11") # Linux, BSD
ENDMACRO(ADM_PREBUILD)
#
#
#
MACRO(ADM_MAIN_APP)
        ADD_EXECUTABLE(avidemux3_${QT_EXTENSION}  ${ADM_EXE_SRCS})

ENDMACRO(ADM_MAIN_APP)
#

MACRO(ADM_POSTBUILD)
	ADM_INSTALL_BIN(avidemux3_${QT_EXTENSION})
ENDMACRO(ADM_POSTBUILD)
