// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "ffVAEnc_HEVC.h"
bool  ffvaHEVC_encoder_jserialize(const char *file, const ffvaHEVC_encoder *key){
admJson json;
json.addUint32("gopsize",key->gopsize);
json.addUint32("bframes",key->bframes);
json.addUint32("bitrate",key->bitrate);
json.addUint32("max_bitrate",key->max_bitrate);
json.addUint32("quality",key->quality);
json.addUint32("rc_mode",key->rc_mode);
return json.dumpToFile(file);
};
bool  ffvaHEVC_encoder_jdeserialize(const char *file, const ADM_paramList *tmpl,ffvaHEVC_encoder *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
