// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "vorbis_encoder.h"
bool  vorbis_encoder_jserialize(const char *file, const vorbis_encoder *key){
admJson json;
json.addUint32("bitrate",key->bitrate);
json.addUint32("mode",key->mode);
json.addFloat("quality",key->quality);
return json.dumpToFile(file);
};
bool  vorbis_encoder_jdeserialize(const char *file, const ADM_paramList *tmpl,vorbis_encoder *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
