// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
bool limitDropCount;
int32_t maxDropCount;
int32_t threshold;
bool evaluate;
}decimateFrame;
