// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList decimateFrame_param[]={
 {"limitDropCount",offsetof(decimateFrame,limitDropCount),"bool",ADM_param_bool},
 {"maxDropCount",offsetof(decimateFrame,maxDropCount),"int32_t",ADM_param_int32_t},
 {"threshold",offsetof(decimateFrame,threshold),"int32_t",ADM_param_int32_t},
 {"evaluate",offsetof(decimateFrame,evaluate),"bool",ADM_param_bool},
{NULL,0,NULL}
};
