// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList colorTemp_param[]={
 {"temperature",offsetof(colorTemp,temperature),"float",ADM_param_float},
 {"angle",offsetof(colorTemp,angle),"float",ADM_param_float},
{NULL,0,NULL}
};
