// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "jpeg_encoder.h"
bool  jpeg_encoder_jserialize(const char *file, const jpeg_encoder *key){
admJson json;
json.addUint32("pixelFormat",key->pixelFormat);
json.addUint32("quantizer",key->quantizer);
return json.dumpToFile(file);
};
bool  jpeg_encoder_jdeserialize(const char *file, const ADM_paramList *tmpl,jpeg_encoder *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
