// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList jpeg_encoder_param[]={
 {"pixelFormat",offsetof(jpeg_encoder,pixelFormat),"uint32_t",ADM_param_uint32_t},
 {"quantizer",offsetof(jpeg_encoder,quantizer),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
