// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList fadeFromImage_param[]={
 {"startTime",offsetof(fadeFromImage,startTime),"uint32_t",ADM_param_uint32_t},
 {"endTime",offsetof(fadeFromImage,endTime),"uint32_t",ADM_param_uint32_t},
 {"effect",offsetof(fadeFromImage,effect),"uint32_t",ADM_param_uint32_t},
 {"direction",offsetof(fadeFromImage,direction),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
