// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList chromashift_param[]={
 {"u",offsetof(chromashift,u),"int32_t",ADM_param_int32_t},
 {"v",offsetof(chromashift,v),"int32_t",ADM_param_int32_t},
{NULL,0,NULL}
};
