// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "chromashift.h"
bool  chromashift_jserialize(const char *file, const chromashift *key){
admJson json;
json.addInt32("u",key->u);
json.addInt32("v",key->v);
return json.dumpToFile(file);
};
bool  chromashift_jdeserialize(const char *file, const ADM_paramList *tmpl,chromashift *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
