// automatically generated by admSerialization.py do not edit
#ifndef ADM_teleCide_CONF_H
#define ADM_teleCide_CONF_H
typedef struct {
uint32_t order;
uint32_t back;
uint32_t back_saved;
uint32_t guide;
float gthresh;
uint32_t post;
bool chroma;
float vthresh;
float vthresh_saved;
float bthresh;
float dthresh;
bool blend;
uint32_t nt;
uint32_t y0;
uint32_t y1;
uint32_t hints;
bool show;
bool debug;
}teleCide;
#endif
