// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList delogo_param[]={
 {"xoff",offsetof(delogo,xoff),"uint32_t",ADM_param_uint32_t},
 {"yoff",offsetof(delogo,yoff),"uint32_t",ADM_param_uint32_t},
 {"lw",offsetof(delogo,lw),"uint32_t",ADM_param_uint32_t},
 {"lh",offsetof(delogo,lh),"uint32_t",ADM_param_uint32_t},
 {"band",offsetof(delogo,band),"uint32_t",ADM_param_uint32_t},
 {"show",offsetof(delogo,show),"bool",ADM_param_bool},
{NULL,0,NULL}
};
