// automatically generated by admSerialization.py, do not edit!
#include "ADM_default.h"
#include "ADM_paramList.h"
#include "ADM_coreJson.h"
#include "delogo.h"
bool  delogo_jserialize(const char *file, const delogo *key){
admJson json;
json.addUint32("xoff",key->xoff);
json.addUint32("yoff",key->yoff);
json.addUint32("lw",key->lw);
json.addUint32("lh",key->lh);
json.addUint32("band",key->band);
json.addBool("show",key->show);
return json.dumpToFile(file);
};
bool  delogo_jdeserialize(const char *file, const ADM_paramList *tmpl,delogo *key){
admJsonToCouple json;
CONFcouple *c=json.readFromFile(file);
if(!c) {ADM_error("Cannot read json file");return false;}
bool r= ADM_paramLoadPartial(c,tmpl,key);
delete c;
return r;
};
