// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList raw_muxer_param[]={
 {"requestAnnexB",offsetof(raw_muxer,requestAnnexB),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
