// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
uint32_t requestAnnexB;
uint32_t separateFiles;
uint32_t maxDigits;
uint32_t extIdx;
}raw_muxer;
