// automatically generated by admSerialization.py, do not edit!
// automatically generated by admSerialization.py do not edit
#ifndef ADM_resampleFps_CONF_H
#define ADM_resampleFps_CONF_H
typedef struct {
uint32_t mode;
uint32_t newFpsDen;
uint32_t newFpsNum;
}resampleFps;
#endif
